### PR TITLE
Rework for Tabstrip regression issue

### PR DESCRIPTION
**Pull request by leigh-pointer**
Fix for TabPanel is not updating the UI. [#4778](https://github.com/oqtane/oqtane.framework/issues/4778) [#4828](https://github.com/oqtane/oqtane.framework/issues/4828)

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer there are a lot of third party modules which use the TabStrip component... I am concerned that these recent changes will result in regression issues / broken functionality.

**Comment by sbwalker** [comment]
After more testing (without applying #4871) there are also UX issues with adding new pages and editing existing pages. I am going to rollback #4828 as there are too many ripple effects to this change.

**Comment by leigh-pointer** [comment]
@sbwalker i have been extremely careful about backward compatibility. I have tested with the framework and external modules.

**Comment by sbwalker** [comment]
@leigh-pointer if you select Add Page from the Control Panel and then select to change the Parent field to a different page, all of the fields on the Settings tab disappear. Do you see this issue as well?

**Comment by leigh-pointer** [comment]
@sbwalker no, everything works fine.

**Comment by sbwalker** [comment]
after applying this PR... if you select Add Page from the Control Panel and then select to change the Parent field to a different page, the Settings tab is no longer highlighted:

image

**Comment by sbwalker** [comment]
#4872 also seems to have been caused by the recent changes to the TabStrip component.

**Comment by sbwalker** [comment]
@leigh-pointer I rolled back #4871 and #4828 as there are too many regression problems

**Pull request merged**
