### PR TITLE
Fix the localization manager resolution

### PR DESCRIPTION
**Pull request by hishamco**
Addresses https://github.com/oqtane/oqtane.framework/discussions/1094

### CODE REVIEW

**Comment by hishamco** [comment]
@sbwalker please merge this ASAP, it's a blocker

**Comment by isolution1** [comment]
The new error is still related to localization
InvalidOperationException: Sequence contains no elements
System.Linq.ThrowHelper.ThrowNoElementsException()
System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
Oqtane.Pages.HostModel.OnGet() in _Host.cshtml.cs
+
                    **var defaultLanguage = languages.Where(l => l.IsDefault).SingleOrDefault() ?? languages.First();**

**Comment by sbwalker** [comment]
These issues all seem to be related to the refactoring in #1071. @hishamco I would suggest you clear the connection string in your local installation and do a clean install to test your changes.

**Comment by hishamco** [comment]
Hope to do a final test on a clean installation

**Comment by sbwalker** [comment]
I just fixed the issue in #1096

**Pull request merged**
