### PR TITLE
Path Separator Char

### PR DESCRIPTION
**Pull request by leigh-pointer**
Path.AltDirectorySeparatorChar implementation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=915) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=915) before we can accept your contribution.<br/><br/>:x: leigh-pointer [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=915)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.framework?pullRequest=915) it.</sub>

**Comment by hishamco** [comment]
@sbwalker can we setup CI/CD so something like could be tested across Windows, Linux and Mac

**Comment by sbwalker** [comment]
@leigh-pointer thank you for submitting this PR. Did you try running Oqtane on WebAssembly after making these changes? I am asking because when running on WebAssembly the application is running inside the browser - not on a server. So I am curious what Path.DirectorySeparatorChar will return in this case. For example if your browser was running on a Windows client and Oqtane was running on a Mac as the server, would Path.DirectorySeparatorChar return "\\" in the client?

**Comment by sbwalker** [comment]
I think it may be better to not handle path strings in the Client - and do it on the server instead, at the location where the path is being used. There is a utility method Utilities.PathCombine() which is used in the server project already in many places to create a properly localized string path for the server environment.

**Review by jimspillane — CHANGES_REQUESTED** [review]
@leigh-pointer please check the latest commit for a few additional files and changes that do not apply to this PR.

**Comment by sbwalker** [comment]
@leigh-pointer Thank you for the submission but I cannot merge this PR for the reasons @jimspillane outlined above - it contains a bunch of extra files, etc.. which are not related to the item you were trying to address.

**Comment by sbwalker** [comment]
Interesting note from the docs:

https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=net-5.0

When you are using .NET Core to develop applications that run on multiple platforms:

If you prefer to hard-code the directory separator character, you should use the forward slash ("/") character. It is the only recognized directory separator character on Unix systems, as the output from the example shows, and is the AltDirectorySeparatorChar on Windows.

**Comment by hishamco** [comment]
I think @jimspillane to similar note in one of the issues if I remembered

**Comment by sbwalker** [comment]
@leigh-pointer I was not able to merge this PR because it contained a bunch of other unrelated files - however if you would like to submit a new PR which addresses the issue of cross platform file paths it would be very helpful.

**Comment by leigh-pointer** [comment]
@sbwalker files are ready to go. 4 in total.  currently cant push to dev

**Comment by sbwalker** [comment]
@leigh-pointer is there a technical reason you can't push to dev?

**Comment by leigh-pointer** [comment]
@sbwalker  Technical reason is "denied"
_Pushing dev
Remote: Permission to oqtane/oqtane.framework.git denied to leigh-pointer.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/oqtane/oqtane.framework.git/': The requested URL returned error: 403
Pushing to https://github.com/oqtane/oqtane.framework.git_

**Comment by sbwalker** [comment]
It sounds like you are trying to do a direct commit to the repo rather than using the pull request process. Is it possible for you to use the PR method?

**Pull request closed without merging**
