### PR TITLE
Oqtane.Migrations -> Oqtane.Database.Migrations

### PR DESCRIPTION
**Pull request by hishamco**
@cnurse just moved `Migrations` to proper namespace which is make sense while the migrations are database related. I tested a new installation after this change to make sure nothing is broken

### CODE REVIEW

**Comment by sbwalker** [comment]
@hishamco this looks fine to me... but I will let @cnurse weigh in before I merge

**Comment by sbwalker** [comment]
@hishamco I am going to close this as it appears #1383 replaces it

**Comment by hishamco** [comment]
I revise the new updates? the migrations are still on its own namespace not Database one

**Comment by sbwalker** [comment]
I would prefer to leave the namespaces as is

**Comment by hishamco** [comment]
Ok, one more thing why there's a dependency on Sqlite on the server projects, are there some changes last few weeks?

**Comment by hishamco** [comment]
FYI I'm unable to install Oqtane, "Value cannot be null. (Parameter 'type')" show up?

**Comment by sbwalker** [comment]
@hishamco install on which database? You are sure your appsettings.json is in the correct form? There have been a lot of changes to appsettings.json for 2.1

**Comment by hishamco** [comment]
```
{
  "Runtime": "Server",
  "Database": {
    "DefaultDBType": "Oqtane.Database.SqlServer.SqlServerDatabase, Oqtane.Database.SqlServer"
  },
  "ConnectionStrings": {
    "DefaultConnection": ""
  },
  "Installation": {
    "DefaultAlias": "",
    "HostPassword": "",
    "HostEmail": "",
    "SiteTemplate": "",
    "DefaultTheme": "",
    "DefaultContainer": ""
  },
  "Localization": {
    "DefaultCulture": "en"
  },
  "AvailableDatabases": [
    {
      "Name": "LocalDB",
      "ControlType": "Oqtane.Installer.Controls.LocalDBConfig, Oqtane.Client",
      "DBType": "Oqtane.Database.SqlServer.SqlServerDatabase, Oqtane.Database.SqlServer"
    },
    {
      "Name": "SQL Server",
      "ControlType": "Oqtane.Installer.Controls.SqlServerConfig, Oqtane.Client",
      "DBType": "Oqtane.Database.SqlServer.SqlServerDatabase, Oqtane.Database.SqlServer"
    },
    {
      "Name": "SQLite",
      "ControlType": "Oqtane.Installer.Controls.SqliteConfig, Oqtane.Client",
      "DBType": "Oqtane.Database.Sqlite.SqliteDatabase, Oqtane.Database.Sqlite"
    },
    {
      "Name": "MySQL",
      "ControlType": "Oqtane.Installer.Controls.MySQLConfig, Oqtane.Client",
      "DBType": "Oqtane.Database.MySQL.MySQLDatabase, Oqtane.Database.MySQL"
    },
    {
      "Name": "PostgreSQL",
      "ControlType": "Oqtane.Installer.Controls.PostgreSQLConfig, Oqtane.Client",
      "DBType": "Oqtane.Database.PostgreSQL.PostgreSQLDatabase, Oqtane.Database.PostgreSQL"
    }
  ]
}
```

I didn't change anything

**Comment by sbwalker** [comment]
The only thing which seems to be missing is:

"RenderMode": "ServerPrerendered",

**Comment by hishamco** [comment]
Same thing, I will try to `git fetch` again

**Comment by hishamco** [comment]
Last thing seems the data providers project have been removed, so where can I find the implementation for them?

**Comment by sbwalker** [comment]
There is a Oqtane.Databases.sln which contains all the database projects. The repo contains all of the data providers in the same location as previously.

**Comment by hishamco** [comment]
> The repo contains all of the data providers in the same location as previously.

Could you please point me to the repo?

**Comment by sbwalker** [comment]
they are in the main repo: https://github.com/oqtane/oqtane.framework you can see the folders for Oqtane.Database.MySQL, Oqtane.Database.PostgreSQL, etc...

**Comment by hishamco** [comment]
Seems the internet issue causes some git issue the repo still not fetched totally .. thanks a lot

**Comment by sbwalker** [comment]
To answer the question on SQLite...

SQLite has a "runtimes" dependencies which is not loaded automatically by the AssemblyLoadContext Load methods.  This is a known issue see:

https://github.com/dotnet/runtime/issues/13015
https://github.com/dotnet/runtime/issues/3660
https://github.com/dotnet/runtime/issues/3659

The simplest solution for this problem was to add a Nuget Package reference to Oqtane.Server to ensure that the dependency graph is correct. The downside is that Sqlite “core” components are always deployed to the /bin whether or not they are actually used - but this is an acceptable compromise in order to enable this database.

**Comment by hishamco** [comment]
Are other database providers loaded on demand?

**Comment by sbwalker** [comment]
Yes, all database providers are deployed and loaded on demand.

**Comment by hishamco** [comment]
Strange!! I will have a look to SQLite and see why it can't be loaded

**Comment by sbwalker** [comment]
I am not concerned about this... I am fine releasing 2.1 with this configuration.

**Pull request closed without merging**
