### PR TITLE
Supported cultures perf

### PR DESCRIPTION
**Pull request by hishamco**
@sbwalker I pushed a PR that I pointed in https://github.com/oqtane/oqtane.framework/discussions/1258#discussioncomment-637247 frankly I'm not sure if pushed before or something goes wrong during the merge

### CODE REVIEW

**Comment by sbwalker** [comment]
@hishamco you appear to be correct as #1247 was included in the 2.0.2 release - but the change does not appear to exist in the latest Dev code. Something went wrong in the merge or conflict resolution for #1239. Perhaps @cnurse might have a clue of what happened.

**Comment by hishamco** [comment]
No problem, luckly I find something lost from what I committed ;)

**Comment by sbwalker** [comment]
Actually, I am mistaken in my last comment. The code change from #1247 is in the Dev branch https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Server/Infrastructure/LocalizationManager.cs - so I dont think any changes were lost. That being said, there seems to be something wrong with this PR as the changes seem to reference an older version of Oqtane code: https://github.com/oqtane/oqtane.framework/pull/1263/commits/0b5d1f9f098c2febefdf73655482042b23adf49c. Are you sure your local code is 100% up to date?

On a different note I had already optimized GetSupportedCultures here https://github.com/oqtane/oqtane.framework/blob/dev/Oqtane.Server/Infrastructure/LocalizationManager.cs - the change being that the framework should only consider subfolders under /bin which actually contain an Oqtane.Client.resources.dll satellite assembly to be valid. If there are culture subfolders under /bin and they are empty then those culture should not be included.

**Comment by hishamco** [comment]
> Actually, I am mistaken in my last comment

Seems you are right, seems I forgot to push the PR, thanks anyway, you could merge the PR now after the last commit I added

**Comment by hishamco** [comment]
@sbwalker please merge #1264 after you merge this PR, basically we should remove the English (default language) from lanaguages list

**Comment by sbwalker** [comment]
this PR breaks the behavior I described above - the framework should only consider subfolders under /bin which actually contain an Oqtane.Client.resources.dll satellite assembly. If there are culture subfolders under /bin and they are empty then those cultures should not be included.

**Comment by sbwalker** [comment]
this logic would also be a performance regression, as it is getting a list of all cultures and then doing an individual GetDirectory() on each one... as opposed to doing a single GetDirectory() call with a very narrow filter.

**Comment by hishamco** [comment]
> If there are culture subfolders under /bin and they are empty then those cultures should not be included

I expect you will say that similarlly any folder contains `Oqtane.Client.resources.dll` will be considered as culture even it's name not a proper culture. I think I will add extra condition to ensure that satellite assembly is included

**Comment by hishamco** [comment]
> this logic would also be a performance regression, as it is getting a list of all cultures and then doing an individual GetDirectory() on each one... as opposed to doing a single GetDirectory() call with a very narrow filter.

Assume we have 100 cultures, and 10 supported cultures and each contains 10 modules

This PR will do a check 100 times, while yours will do 10 * 11 = 110, so if this increased dramatically

No. Cultures < Supported Cultures No. x Oqtane Satellite Assemblies No. x Oqtane Modules Satellite Assemblies No.

**Comment by hishamco** [comment]
Furthermore this method is static and it will get call once

**Comment by hishamco** [comment]
Perhaps your PR will win in case the has few cultures, either way we need Oqtane to get better in terms of PERF, I can do a benchmarks if it's necessary

**Comment by sbwalker** [comment]
This PR  changes the intended functionality - it does not restrict the SupportedCultures to only those subfolders which contain Oqtane.Client.resources.dll. I do not see the benefits of the other changes so my preference is to close this PR ( as it does not fix a bug and the performance improvments are highly debatable ).

**Comment by hishamco** [comment]
I will close this PR and start a new one that will add some other benifit

**Pull request closed without merging**
