### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hishamco**
@sbwalker seems we forgot to update the version in README.md

### CODE REVIEW

**Comment by sbwalker** [comment]
@hishamco I actually did not forget to update... I do not plan on posting the actual 2.0 release until tomorrow.

**Comment by hishamco** [comment]
I see, did you plan to write a blog post too

**Comment by sbwalker** [comment]
yes, I have most of the blog post written already - it will be posted tomorrow

**Comment by hishamco** [comment]
Waiting for your post and session then

**Pull request merged**
