### PR TITLE
[FIX] - Looping issue with OnSelect if EventCallback is used #3010

### PR DESCRIPTION
**Pull request by vnetonline**
Made OnSelect an Action instead of EventCallback which causes the lopping issue

### CODE REVIEW

**Comment by sbwalker** [comment]
@vnetonline I do not believe this is the correct fix - please see my comments on #3010

**Comment by sbwalker** [comment]
I already checked in a fix in #3024 earlier as I do not believe the OnSelect call is necessary in either OnInitialized() or OnParametersSet()

**Comment by vnetonline** [comment]
This pull requests also moves SetImage() to before the event fires and removes the redundant SateHasChanged so that the parent page can get the image from the fileManager rather then making a call through FileService to retire the image again.

**Comment by vnetonline** [comment]
Create another pull request just for moving the SetImage() before the event fires and removing the redundant StateHasChanged

**Pull request closed without merging**
