### PR TITLE
Oqtane service collection extensions

### PR DESCRIPTION
**Pull request by hishamco**
This include:

- Add Oqtane `ServiceCollection` extension methods such as: `AddOqtaneModules()`, `AddOqtaneThemes()` .. etc

- Add missing theme types to the modules assemblies

### CODE REVIEW

**Comment by sbwalker** [comment]
this is a very nice refactoring to clean up and separate the startup logic

**Comment by hishamco** [comment]
Thanks, hope you see more contribution in the upcoming future ;)

**Comment by hishamco** [comment]
@sbwalker I forgot to tell you that during doing this refactoring I notice that the client-side project has part of what I did in the server-side project, is this by intention? I will submit another PR for fixing that too

**Comment by sbwalker** [comment]
Yes this is intentional. Oqtane can be run in both server-side and client-side hosting models. To run in client-side you need to change your Solution Configuration from Debug to Wasm then recompile and run. This uses conditional compilation which is mostly restricted to the Startup methods

**Comment by sbwalker** [comment]
After merging the changes as part of this PR I am having difficulty with my local environment. It is throwing errors when I run related to:

An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.Extensions.DependencyInjection.dll
Cannot instantiate implementation type 'Microsoft.Extensions.Hosting.BackgroundService' for service type 'Microsoft.Extensions.Hosting.IHostedService'

**Comment by sbwalker** [comment]
So the problem is that the refactored code:

var serviceTypes = assembly.GetTypes(hostedServiceType);

does not have the same behavior as the previous code:

                Type[] servicetypes = assembly.GetTypes()
                    .Where(item => item.GetInterfaces().Contains(typeof(IHostedService)))
                    .ToArray();

The GetTypes() overload used in the refactoring returns a much larger collection of types than the former code.

**Comment by sbwalker** [comment]
resolved in #185

**Comment by hishamco** [comment]
Sorry I just prepared a fit for that two days ago, unfortunately the Internet cable has an issue, so that's why I didn't push the pr

**Comment by hishamco** [comment]
> Yes this is intentional.

So I need to do similar thing in the client-side as well

**Comment by hishamco** [comment]
@sbwalker I just notice in that client-side project that there's no notion of registering themes, modules, hosted services. Is this intentionally or a bug?

Please confirm before push my pr

**Comment by sbwalker** [comment]
This is intentional. The client-side project does not need to register themes, modules, or hosted services - only the Server project needs them, and the Server project always runs on the server ( whereas the Client project will either run on the server in server-side Blazor or in the browser in client-side Blazor ).

**Pull request merged**
