### PR TITLE
Use ModuleMessage component everywhere

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by hishamco** [comment]
@sbwalker I just refactor the File Manager to you use the proposed alert component, if sound good to you I can refactor all the places to use the new component

**Comment by sbwalker** [comment]
A component already exists for this functionality - the ModuleMessage component. It is used throughout the UI already- usually by calling the AddModuleMessage helper method - but also as a standard component.

**Comment by hishamco** [comment]
I didn't know about it, let me check ...

**Comment by hishamco** [comment]
@sbwalker it's ready from my side, just one question why you create a `Get` and `Set` methods on the component while you can get or set parameters directly from the component instance?!!

**Comment by sbwalker** [comment]
@hishamco the SetModuleMessage() method is only intended to be used in one specific case - when a module developer calls the AddModuleMessage() helper which then needs to traverse to the ModuleInstance parent component and set the Message/Type properties on its ModuleMessage component. There may be a better way to implement this. Regardless, in all other cases the ModuleMessage component should be used in the standard way - by setting the parameter values directly and not using the SetModuleMessage() method. Make sense?

**Comment by hishamco** [comment]
> by setting the parameter values directly and not using the SetModuleMessage() method. Make sense

I did that at the beginning but I got some warnings when I set the parameters directly, let me change it in all the places

**Comment by hishamco** [comment]
Done!!

**Pull request merged**
