### PR TITLE
Fix for Tabpanel is not updating the UI. #4778

### PR DESCRIPTION
**Pull request by leigh-pointer**
Updated the TabStrip and TabPanel so when the ActiveTab parameter is changed the corresponding TabPane is selected.

### CODE REVIEW

**Comment by leigh-pointer** [comment]
@sbwalker Is there a problem with this PR?

**Comment by sbwalker** [comment]
@leigh-pointer I have not had time to test it yet... I have been focusing on the upgrade issues related to .NET 9

**Comment by sbwalker** [comment]
@leigh-pointer I am not sure if this enhancement caused a regression issue or if it is related to something else. Login to a site, go into Edit Mode, select Edit Content on an HtmlText module on the Home page... the rich text editor displays fine... now click the Full Text Editor tab... and then click Rich Text Editor... the rich text editor will no longer be displayed properly:

image

**Comment by leigh-pointer** [comment]
@sbwalker ok, will I look in to it.

**Pull request merged**
