### PR TITLE
Fix #4224: close the control panel after adding a module.

### LINKED ISSUE #4224: [BUG] the control panel mask element won't hide after add a new module into page
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
the control panel mask element won't hide after add a new module into page, user has to click on the page to hide the mask manually.

### Expected Behavior
The dialog mask should be hidden automatically after the control panel closed.

### Steps To Reproduce
1. login as host, click the gear button to open control panel.
2. the control panel will be closed after adding a new module into the page, but the mask still there.
image

### PR DESCRIPTION
**Pull request by zyhfish**
Fix #4224: close the control panel after adding a module.

### CODE REVIEW

**Comment by sbwalker** [comment]
@zyhfish we want to keep the current behavior so that it is possible to add multiple modules without having to re-open the control panel

**Comment by zyhfish** [comment]
Hi @sbwalker , current behavior is the control panel will be closed but just left the dialog mask element display on the page.

I will try to find a solution to keep the control panel open after add the module.

**Comment by leigh-pointer** [comment]
@zyhfish i have looked at the functionality in Edge, Chrome, FireFox, Brave and don't see any mask issue.
What browser are you using ?

**Comment by zyhfish** [comment]
Hi @leigh-pointer , I'm using Chrome, and weird that it's CNR from my end now, it was a persist issue before, could that related to the CDN of bootstrap and the provider update the resource?

**Comment by leigh-pointer** [comment]
@zyhfish I heard something on the interweb about some issues with a few CDN's not performing well. This  must have been the issue.

**Comment by zyhfish** [comment]
Hi @leigh-pointer , I confirmed this is reproducible only with Static render mode. in Interactive mode it works fine, the control panel will keep open after adding a module.

**Pull request closed without merging**
