### PR TITLE
Creation of site fix

### PR DESCRIPTION
**Pull request by chlupac**
-add ~ to site folder name
-check if alias endpoint is alive with ping request

### CODE REVIEW

**Comment by sbwalker** [comment]
I do not want to users to have to add a "~" to their folder names

**Comment by chlupac** [comment]
it's handled automatically

**Comment by sbwalker** [comment]
It is not 100% clear what this pull request was trying to resolve. A few observations:

- the ping service you included to test if an alias is a valid url has security issues. The controller is available for anyone to call and pass any url they desire. This could be abused ( ie. a malicious user could initiate a DOS attack on a url and use your site as a proxy ).

- although it seems like a good idea to validate that an alias is valid, there are a number of use cases where this functionality is not desired. For example, when a user is setting up a site they may want to include a number of aliases which have not yet been configured through DNS yet - as they may plan to do this step later. The system should not restrict the user from entering them. In addition, you should be able to use Oqtane on your local machine without an Internet connection - so requiring an alias to be validated may pose an unnecessary restriction.

**Comment by sbwalker** [comment]
#249 has a number of improvements for creating/editing/deleting sites which should help address some of the items you were trying to resolve in this PR. For example. if you enter an alias value incorrectly, you are now able to access the Edit Site dialog in Site Management to fix the alias value.

**Comment by chlupac** [comment]
Ok, i see than my code is obsolete now, i will close this PR and i will test new update. 

1. This Ping controller is available as other publicly accessible controllers and do not pass any url. I do not see any security problem. Controller returns only "Pong" to any request. How you can use it as proxy?

2. But you are switching to that alias after creation of site and this action  fail, if it not available.

**Pull request closed without merging**
