### PR TITLE
Reduce FOUC between pages

### PR DESCRIPTION
**Pull request by jimspillane**
Convert a relative URL to an absolute URL before testing against the href value.  This will reduce the number of link refreshes if the same URL is used.

### CODE REVIEW

**Comment by sbwalker** [comment]
FOUC = "Flash Of Unstyled Content" - I was not familiar with that term ;) Just so I understand, you are saying that the JavaScript comparison of (link.href !== url) is always true currently because link.href is an absolute url and url is a relative url?

**Comment by jimspillane** [comment]
Yes.  Changing the _url_ parameter to absolute will help stop the reloading the same resource if it is relative.

**Comment by sbwalker** [comment]
would this also be relevant in the includeScript() function?

**Comment by jimspillane** [comment]
Yes. I will change it to run in the includeScript() function too.  Thanks!

**Comment by jimspillane** [comment]
I added a modification that addresses window.interop getting clobbered by the quill-interop when the editor is opened.

**Comment by jimspillane** [comment]
I am going to close this PR because the CSS/JavaScript dependency issue is not resolved with this change

I will submit the namespace modifications in a separate request.

**Pull request closed without merging**
