### PR TITLE
Refactored to method to make the code more DRY.

### PR DESCRIPTION
**Pull request by mikecasas**
This PR is an example of what I mentioned in #736. Just wondering if you want refactorings/PRs like this.

### CODE REVIEW

**Comment by hishamco** [comment]
I prefer to create a UI component for that, let me share what I did ...

**Comment by hishamco** [comment]
I created a draft PR #750, I will try to replace all the strings that made an alert UI from the code, I think this will be better, like what we did in other components

**Comment by sbwalker** [comment]
A component already exists for this functionality - the ModuleMessage component. It is used throughout the UI already- usually by calling the AddModuleMessage helper method - but also as a standard component.

**Comment by mikecasas** [comment]
My original intent was just to clean up some of the repetitive code.

**Comment by sbwalker** [comment]
@mikecasas its a good idea to eliminate repetitive code... you could use the existing ModuleMessage component in the FileManager

**Pull request closed without merging**
