### PR TITLE
Enables boostrap frienldy forms by changing from Table to DIV adding …

### PR DESCRIPTION
**Pull request by thabaum**
...  Enables boostrap frienldy forms by changing from Table to DIV adding

Fixes issue #437 

image

Notes:

More pages can be updates this way for the UI.  This is something that should be done prior to letting it go down the road in some form.

I was thinking about maybe later putting the labels inside the borders.  This has the readonly fix included however you can merge the other PR first then merge this one things should work just fine.

### CODE REVIEW

**Comment by thabaum** [comment]
I have one PR I am creating that does the same thing to the rest of Admin pages and some CSS tune up to go with here as soon as I can figure out how to make them all show up right in a PR from Visual Studio... or copy and paste all the files in github manually.  This PR is an example of what I did for all the pages.

**Comment by sbwalker** [comment]
@thabaum changing the admin UI from tables to divs was deferred until after the MVP release

**Comment by thabaum** [comment]
OK I just wanted to give it a more formal approach.  I have all of the files redone if you want to review.  Nothing special but I think makes more device friendly for now.

The class's I didn't feel I should create for anything without a deeper discussion.  I will add my changed files to this PR in the event you would like to review it as the work is done for a simple tune-up.  Anytime this type of change gets discussed it is a "Breaking Change" so I wanted to make it now while the hood is still up.

**Comment by sbwalker** [comment]
yes please submit for review

**Pull request closed without merging**
