### PR TITLE
Broken link fixed in Readme

### PR DESCRIPTION
**Pull request by alperenbelgic**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=2108) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=2108) before we can accept your contribution.<br/><br/>:x: alperenbelgic [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=2108)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.framework?pullRequest=2108) it.</sub>

**Comment by sbwalker** [comment]
Thank you for reporting this issue. Oqtane has a url mapping feature which is intended to manage the mapping of broken urls. The fact that the link in the readme was not being redirected to the proper location alerted me to a bug which was introduced during the development of 3.1 - which I was able to resolve. This is a good example of how even small documentation-related PRs can be very valuable. I will merge this PR (even though it is not really necessary as the bug has been resolved ).

**Comment by alperenbelgic** [comment]
thanks for your message @sbwalker. I am very glad it helped. while I am writing this comment I'll mention an issue I experienced. once I click and open the link, the page enters a redirection loop, sometimes for 1 or 2 times and sometimes it makes it 6 or 7 times. It redirects to the same URL ending with a question mark and then redirects it back to the original URL a few times then it settles. I don't know if I have a specific state causing this but I used chrome (normal & incognito mode) on windows 11.

**Comment by sbwalker** [comment]
What is the url of the link are you clicking which has this repeated redirect behavior?

**Pull request merged**
