### PR TITLE
FileService fix

### PR DESCRIPTION
**Pull request by chlupac**
Return empty list when directory does not exists  (controller returns null).

### CODE REVIEW

**Comment by sbwalker** [comment]
@chlupac Oqtane uses a specific approach in its API when retrieving collections to communicate status to the client. It returns an empty collection only under the scenario where the parameters passed to the method are valid but result in a filter operation which returns no records. In the event that the parameters passed to a method are invalid or the user does not have permission to access the resource, the method returns null. It is important to be able to differentiate between these 2 scenarios, and it is up to the client to handle them appropriately. Therefore, modifying the FileService to convert a null into an empty collection is not a valid solution as it changes the meaning of the API response and is not consistent with the rest of the API behavior.

**Comment by chlupac** [comment]
Ok, second solution is ` return files?.OrderBy(item => item.Name).ToList();` to be safe and return null
Did you agree with this solution?

**Comment by sbwalker** [comment]
Realistically it would probably be a better practice to implement the default ordering in the Controller method so that it avoids these types of exceptions in the client service layer and also leverages the server processing power. However the framework has been inconsistent in this area, so the solution you suggested above would also be fine.

**Comment by chlupac** [comment]
Why is output ordered? I think it is not necessary.  Third soution is `return files;`

**Pull request closed without merging**
