### PR TITLE
[ENHANCE] - Added IsRead property to Notifications

### PR DESCRIPTION
**Pull request by vnetonline**
To address issue #2974 added IsRead Property to Notifications.

Notifications will be in Bold until they are Viewed upon which they are marked IsRead = true and not bold upon second view.

### CODE REVIEW

**Comment by sbwalker** [comment]
@vnetonline I think you mistakenly added Oqtane.Updater/Program.cs to this PR

**Comment by sbwalker** [comment]
The migration should be versioned [Migration("Tenant.04.00.01.01")] - as it is will be the first migration in the next stabilization release (version 4.0.1)

**Comment by vnetonline** [comment]
@sbwalker as per your suggestion reverted Program.cs and fixed the Version to Tenant.04.00.01.01 and squashed the pull request thanks for stopping the mistake .... apologies!

**Comment by sbwalker** [comment]
@vnetonline I will merge this PR soon... I am trying to stay focused on the Marketplace this week

**Comment by vnetonline** [comment]
> @vnetonline I will merge this PR soon... I am trying to stay focused on the Marketplace this week

Happy to help with the market place if you need help

**Pull request merged**
