### PR TITLE
Redirect on log out #1225 Fix

### PR DESCRIPTION
**Pull request by leigh-pointer**
Currently when logging out on a page that is not visible to an unauthenticated user the login page is displayed, this is correct but seems pointless as the last action was to log out.  

This change handles a more logical redirection when logging out.

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer your changes to LoginBase.cs are valid... but it is now saying there is a conflict based on my recent PR I merged. I am not sure why there is a conflict as I did not modify that file? Perhaps you get the latest changes and then submit this PR again?

**Comment by hishamco** [comment]
He can rebase on dev branch

**Comment by leigh-pointer** [comment]
@sbwalker got the changes, (nice!) 
Redirect should be ok now?

**Comment by sbwalker** [comment]
The PR now says 84 files changed - when there should only be 1 file that changed?

**Comment by leigh-pointer** [comment]
Cancel that something gone silly!

**Pull request closed without merging**
