### PR TITLE
Tenant repository bug

### PR DESCRIPTION
**Pull request by chlupac**
Database Manager bug

### CODE REVIEW

**Comment by mikecasas** [comment]
@chlupac I pulled your branch that you want merged and when I tried adding a new site I got the error below in SiteRouter.razor.

I am not sure if this is related to .NET Core 3.2 preview or something else.


chul1

**Comment by chlupac** [comment]
Did you fill site form correctly ? I think it's not related to my changes.

**Comment by mikecasas** [comment]
You are right. When I create the new site using the Oqtane theme it works fine, but when I use the Blazor theme it crashes because the drop down for Default Layout is empty/

**Comment by chlupac** [comment]
put this bug to issues

**Comment by mikecasas** [comment]
I just did. See #330

**Comment by sbwalker** [comment]
@chlupac is the bug/fix related to the refactoring you did for DatabaseManager or is it related to the change @hishamco made for disallowing changing the master tenant name?

**Comment by chlupac** [comment]
Here is two bugs One is mine, I forgot set flag on tenant, and one is @hishamco with disallowing master tenant name

**Comment by sbwalker** [comment]
Ok, I am not sure about the fix for UpdateTenant - having to use .AsNoTracking() seems like a workaround for a different problem.

**Comment by hishamco** [comment]
> Here is two bugs One is mine, I forgot set flag on tenant, and one is @hishamco with disallowing master tenant name

Could you please let me know what's the bug, so I can fix it now

**Comment by chlupac** [comment]
No, problem is than you cannot have two different entities with same key tracked.
AsNotracked loads detached entity. It's correct.

**Comment by chlupac** [comment]
@hishamco it's fixed

**Comment by sbwalker** [comment]
The key is the TenantId?

**Comment by chlupac** [comment]
yes, look at #328 
when you assign entry state you actually attach entity

**Comment by sbwalker** [comment]
Ok, I understand. The call in GetTenant() uses _db.Tenant.Find(tenantId) which attaches the object to the context with the TenantId... and then later in the UpdateTenant method we are trying to update a different object with the same TenantId

**Pull request merged**
