### PR TITLE
Fix for Module Data Deletion #2734

### PR DESCRIPTION
**Pull request by leigh-pointer**
Updated the framework to delete 
Page -> PageModule -> Module -> 
[ externa Module data + externa Module Settings ]

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer This fix does not seem to be correct - see discussion in #2642 - a module record should only be deleted if there are no other pagemodule records which reference that module on any other pages in a site.

**Comment by leigh-pointer** [comment]
@sbwalker your correct, I keep forgetting that feature.  I will fix it.

**Comment by sbwalker** [comment]
@leigh-pointer this PR still has issues. The PageRepostory.cs (which is server-side) is referencing the IModuleService (which is client-side). I am not even sure how this works - but I am guessing it is because you only tested it on Blazor Server. Either way, this breaks the separation of concerns for client and server and cannot implemented in this way.

**Comment by sbwalker** [comment]
#2872 resolves this issue

**Pull request closed without merging**
