### PR TITLE
Admin UI Update

### PR DESCRIPTION
**Pull request by thabaum**
Updates UI of Admin Modules to use more div tags instead of table tags.

Take it for a test drive, it is different but it works good for now.  I would do so much more to it so this is in no way MVP and I would like to push for it to be included now if possible so I can get used to it.  I know there are more ways to do this.  This is how I am getting to know the framework and github/vs so I can increase productivity when I can help.  

I was able to look at a lot of the UI side of the admin features to see what I might like to do with creating a module.  This code here cleans up the UI area for now if you accept it for a temporary solution until MVP can get all the bells and whistles.

A few files I found already use divs rather than tables so I did not change those.  I did not add class's for naming convention discussions on CSS for this area to style the admin UI as desired easily down the road.

You can leave it open for adjustments for MVP as well...  however this is not MVP!  In my opinion this is a fix as Oqtane should be released with a modern coded UI.  The use of tables reminds me of 1990's webforms.  I only use them when absolutely necessary.  We can use bootstrap to divy up the tables...

**Changing this later is a "breaking change"**

And for a modern version of the UI more razor syntax would probably need to get used to shrink the file sizes even more...

### CODE REVIEW

**Comment by chlupac** [comment]
Why 20 commits ? and it's complete replacement of files, without history. I like changes and work you did, but I do not like this method of PR. You are not using git?

**Comment by thabaum** [comment]
man sorry i been fighting this crap ass software microsoft puts out :)  It should be more easy however i was scared to lose the changes... 

I can redo this again just let me know I have so many repos going my head is starting to spin I want to flush the system out get a fresh start almost :)

**Comment by thabaum** [comment]
I figured the changes would show from the Repo the file differences... I had to upload each file by itself to get the results I wanted with a PR...  I still cannot make it work using VS is my issue.

**Comment by thabaum** [comment]
im getting frustrated a little with branchin, pushin, pullin, applyin, stashin, pottin..did I miss anything?

**Comment by chlupac** [comment]
1. copy files aside, 
2. pull clean repo from oqtane, 
3. make branch, 
4. copy changed files back, 
5. push changes to new branch in your github repo, 
6. make PR.

**Comment by thabaum** [comment]
I thought I tried that a few times I could never get things to sync, kept seeing wrong branches or changes or wrong commits showing up.  But I will try it again.  I cloned the repo but issue is pushing it to a branch that is something I can create a PR, I did it once before I believe just not with so many issues.  

I did not think it was much more different than uploading the changed files in github, in fact I sort of thought it was the point of github... I will redo this up when I have some more time soon.

**Comment by chlupac** [comment]
It reminds me my fight with git and github few months ago when I start to learn it. Then I started develop in Rider and his support of git is good. It helps me lot but it's still challenging adventure to make PR.

**Comment by thabaum** [comment]
It should be the most easy process in the world, just does not make complete sense so I still need to get the workflow down.  I will try to do this tonight if I can.

**Comment by thabaum** [comment]
Figured out a little more about github, you have to create your own pull requests on your fork repo to get all the latest commits... didnt know that so now I can work on the latest version.

**Comment by chlupac** [comment]
@thabaum
https://opensource.com/article/19/7/create-pull-request-github
good tutor how to do it correctly

**Pull request closed without merging**
