### PR TITLE
ModuleCreator: WebAssembly references causes build error in some scenarios. 

### PR DESCRIPTION
**Pull request by chlupac**
Works without them.

error:
Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(195, 5): Duplicate base paths '/' for content root paths .......
https://gitter.im/aspnet/Blazor?at=5e915f6ee24b4d6c44fe1827

### CODE REVIEW

**Comment by hishamco** [comment]
@sbwalker can you check this please

**Comment by sbwalker** [comment]
the references to Microsoft.AspNetCore.Components.WebAssembly and Microsoft.AspNetCore.Components.WebAssembly.Build must be retained or else the external module will not compile:

error

**Comment by hishamco** [comment]
Nah, I told you to check before merge, please Shaun or Pavel create a hot fix for this one

**Comment by sbwalker** [comment]
It was fixed in #428

**Comment by hishamco** [comment]
Thanks for a quick repond

**Pull request merged**
