### PR TITLE
Show LanguageSwitcher if more than one culture

### LINKED ISSUE #1024: Do not show LangSwitcher when only one language is defined
@hishamco what do you think about it?
image

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #1024

### CODE REVIEW

**Comment by chlupac** [comment]
Sorry, but why in ControlPanel? Change it in LanguageSwitcher.razor

```c#
@if (_supportedCultures?.Count() > 1)  // HERE
{
    <div class="btn-group" role="group">
        <button id="btnCultures" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="oi oi-globe"></span>
        </button>
        <div class="dropdown-menu" aria-labelledby="btnCultures">
            @foreach (var culture in _supportedCultures)
            {
                <a class="dropdown-item @(CultureInfo.CurrentUICulture.Name == culture.Name ? "active" : String.Empty)" href="#" @onclick="@(async e => await SetCultureAsync(culture.Name))">@culture.DisplayName</a>
            }
        </div>
    </div>
}
```

**Comment by hishamco** [comment]
Oops I thought that switcher button in the ControlPanel, it's my bad ;)

**Comment by hishamco** [comment]
@sbwalker could we merge this

**Comment by sbwalker** [comment]
I took a few days vacation with my family to end 2020 and I did not bring my laptop... I will return home tomorrow and will be able to catch up on all PR reviews, issues, etc...

**Comment by hishamco** [comment]
Take your time and enjoy with your vacation

**Pull request merged**
