### PR TITLE
UI search control enhancement

### PR DESCRIPTION
**Pull request by thabaum**
This is a fairly simple yet powerful new Search UI control component that can be utilized across the Oqtane Framework.  It comes packed with about every feature a basic search component could ask for and then some.

Features included:
- Localization
- Accessibility
- Client-Side User Input Sanitizing
- Enable/Disable Button
- Enable/Disable Button Icon
- Right/Left Button Placement
- Search-As-You-Type
- Enable/Disable Search Case Sensitivity
- Enable/Disable Enter Key
- Enable/Disable and set timing of De-bouncing (delay before searching using the Search as you type feature)
- Minimum and Maximum Characters
- Ease of styling using the `app-search` class wrapper
- Set Data Types to Search from data sources
- Reusable throughout the Framework and Module development process.
- 

To use it set the parameters in the component as follows using all the allowed parameters you wish to change from default:

```
<Search DataSource="@myData"
        IsSearchEnabled="true"
        MinCharacters="3"
        InputValidationRegex="^[a-zA-Z0-9\s]*$"
        Placeholder="Search..."
        InputAriaLabel="Search input"
        ButtonAriaLabel="Search"
        ButtonToolTip="Search"
        ButtonPosition="right"
        IconPosition="left"
        ShowSearchButton="true"
        EnterKeyEnabled="true"
        ResultsAsTyped="false"
        DebounceEnabled="false"
        CaseSensitive="false"
        @bind-searchTerm="@searchTerm"
        ItemTypes='new List<string> { "Name" }'
        InputTabIndex = "0"
        ButtonTabIndex = "1"
        OnSearchResultsChanged="@HandleSearchResults" />
```

Along with the following code behind similar to:
```
private IEnumerable<object> myData;
private string searchTerm;
private void HandleSearchResults(IEnumerable<object> results)
{
    // Handle search results...
}
```

In this PR I also added an example use case to the `Page Management - Index.razor` file to filter page results.

If there are more than one ItemTypes you would like the search to filter this can be set as well.  I was thinking it would be nice to have another dropdown to select which type of results you want to filter.

I didnt want to go too crazy until the concept was accepted initially then improve upon it down the road.

And use it with a table, pager... to filter results.

Here is a more step-by-step how I used to use this search control:

**1. Initialize your data**
`private IEnumerable<object> allData;`

**2. Initialize your search term:**
`private string searchTerm;`

**3. Handle Search Results:**
```
private void HandleSearchResults(IEnumerable<object> filteredDataList)
{
    var filteredData = filteredDataList.Cast<YourDataType>();
    // Handle filtered data...
}
```

4. Use the Search Component:
```
<Search DataSource="@allData"
        ItemTypes='new List<string> { "Name" }'  // Item Type from Data Source to Filter.
        IsSearchEnabled="true"
        ResultsAsTyped="true"
        CaseSensitive="false"
        MinCharacters="3"
        @bind-searchTerm="@searchTerm"
        OnSearchResultsChanged="@HandleSearchResults" />
```
5. Initialize your data in OnInitializedMethod:
```
protected override void OnInitialized()
{
    allData = YourActualDataSource.ToList();
    displayList = allData;
}
```
6. Update displayList in HandleSearchResults Method:
```
private void HandleSearchResults(IEnumerable<object> filteredDataList)
{
    displayList = filteredDataList.Cast<YourDataType>().ToList();
}
```
**7. Display the results:** 
Use displayList as the data source for your table, pager or other components that will display the results.
```
  <Pager Items="@displayList">
        // Header, Columns and Rows...
  </Pager>
```

Of coarse you can rename variables to make sense for the component you are working on as I used `pageList` and `allResults` in my example component to use this search control for demonstration purposes.

Everything is passed as an object so you can pass Pages, Modules, Sites, Tenants... making this component re-usable.

Is it the best thing since sliced bread?! I beg to differ as the bread lover I am.  But it can get the job done as is.

I am hoping to see this change a lot if it gets added in ways that makes me learn as I go.

Some issues will be when you set certain settings you may not get the results you expect.

Such as the Search-As-You-Type feature with Debouncing enabled and minimum characters set.  You will need this set to 0 minimum characters to allow refreshing on a space bar.

the searchTerm will not always stay present after a search has been done do to different settings being applied.   However most of this has been worked out, this is where I hope others can improve this UI.

Use Examples Notes:

- Search as you type shows results as you type.  Debouncing is an option to enable/disable that works here as well but you may not like the current results.  You can set the time in milliseconds.
- No button and no search as you type, still an option because you enable the Enter Key functionality and you can type then hit enter to see results.
- Enter Key Enabled works with or without button (not Search-as-you-type since it searches all the time)
- Buttons left or right of input with or without text or icon as you please.
- Minimum Characters and Maximum Character support (defaults currently are set at 3-50)  I put 0 for the Page Management Example which also allows you to get all results.  At times having min chars may not work like you hope, set to 0 which disables it.

Here is a complete list of current parameters and their default values:
```
    // Search settings
    [Parameter]
    public bool IsSearchEnabled { get; set; } = true;

    [Parameter]
    public bool ResultsAsTyped { get; set; } = false;

    [Parameter]
    public bool CaseSensitive { get; set; } = false;

    [Parameter]
    public bool EnterKeyEnabled { get; set; } = true;

    [Parameter]
    public bool DebounceEnabled { get; set; } = false;

    [Parameter]
    public int DebounceTime { get; set; } = 500; // Time in milliseconds

    // Search data
    [Parameter]
    public IEnumerable<object> DataSource { get; set; }

    [Parameter]
    public List<string> ItemTypes { get; set; }

    // Search term settings
    [Parameter]
    public string SearchTerm { get; set; }

    [Parameter]
    public int MinCharacters { get; set; } = 3;

    [Parameter]
    public int MaxCharacters { get; set; } = 50;

    [Parameter]
    public string InputValidationRegex { get; set; } = @"^[a-zA-Z0-9\s]*$";

    // UI settings
    [Parameter]
    public bool ShowSearchButton { get; set; } = true;

    [Parameter]
    public string SearchIcon { get; set; } = Icons.MagnifyingGlass;

    [Parameter]
    public string IconPosition { get; set; } = "left";

    [Parameter]
    public string ButtonPosition { get; set; } = "right";

    [Parameter]
    public bool ShowSearchIcon { get; set; } = true;

    [Parameter]
    public bool ShowButtonText { get; set; } = true;

    [Parameter]
    public string Placeholder { get; set; } = "Search...";

    [Parameter]
    public int InputTabIndex { get; set; } = 0;

    [Parameter]
    public int ButtonTabIndex { get; set; } = 1;

    [Parameter]
    public string InputAriaLabel { get; set; } = "Search input";

    [Parameter]
    public string ButtonAriaLabel { get; set; } = "Search";

    [Parameter]
    public string ButtonLabel { get; set; } = "Search";

    [Parameter]
    public string ButtonToolTip { get; set; } = "Search";

    [Parameter]
    public bool EnableAutocomplete { get; set; } = true;

    // Callbacks
    [Parameter]
    public EventCallback<string> OnSearch { get; set; }

    [Parameter]
    public EventCallback<string> SearchTermChanged { get; set; }

    [Parameter]
    public EventCallback<IEnumerable<object>> OnSearchResultsChanged { get; set; }
```

I wont provide complete documentation until this gets finalized as I have to be prepared for a crash and burn on some if not all of it.  Pull the dents out as we go maybe this can help get us all closer to our finish lines.

Look forward to feedback and any questions I will do my best to answer.

Thanks again for EVERYONE's contribution towards this project over the years. I look forward to the upcoming release using .NET 8.  

One last thought is there is a "button maker" i created I was thinking about porting to another UI control similar to this with all the bells and whistles I can afford to throw at it in a given amount of time.  Probably take me a day or two depending on how this PR goes and feedback towards this idea as well.

I encourage anyone and everyone to take this for a spin and help make it even better!

OK, hitting "create pull request" button now, please dont hurt me too bad ;) but dont hold back either as I can take it!

### CODE REVIEW

**Comment by sbwalker** [comment]
@thabaum I am pasting my comments from the Issue here:

This looks interesting... this seems to be a natural fit as part of the Pager component (which is essentially how you implemented it in the screen shots) - are there any other scenarios where it would be used? It seems like a quick win to integrate it with the Pager to allow all of the Admin pages to benefit from search capabilities.

In regards to UI components, the philosophy behind Oqtane is to keep the core framework as small and lean as possible (for performance reasons). Originally I did not want to include any UI components at all. However based on the fact that Oqtane includes an Admin UI, I concluded that it would be necessary to include a limited number of UI components to help with maintainability and consistency for the admin experience. But to be clear, the main goal from a UI perspective is to avoid creating UI components for Oqtane - and to provide the integration capability so that developers can use their preferred third party UI component libraries.

If you have the motivation to create a native UI component library for Oqtane, you could certainly create it as a separate project. It could even be packaged as a module for easy installation into Oqtane.

**Comment by thabaum** [comment]
@sbwalker 

# But to be clear, the main goal from a UI perspective is to avoid creating UI components for Oqtane - and to provide the integration capability so that developers can use their preferred third party UI component libraries.

I understand that Oqtane is to be lean, however using Blazor things should be re-usable components UI or not.  This really should be usable code for any search feature for about any module I was hoping, not just page but any data which is why I created it in a generic way using `IEnumerable<object>` so  you can pass it what you need, and modify this component into another component if necessary to fit the job at hand.

I am all for third party, but another goal of Oqtane is to NOT use third party as things change in licensing.  I hope Oqtane will never change this licensing which is why I invested in this for the community.

Why not have a basic set of UI components that Oqtane uses to demonstrate use and allow a developer to delete it, modify it, use it?

I was actually wanting to open this discussion in a meeting.  Because I also wanted to break away the "Button" features I created in this into a Button Component for Oqtane.

And also enhance the pager and other UI components to match use cases presented by other UI libraries.  I was going to create a basic "Charts" component as well as I have this somewhere in my pile of past code I can dig out for Pie and Bar charts.  I can create these from scratch with CSS pretty much and some logic to go with created in C#.

From my understanding Oqtane Framework:
 - does NOT want to have third party solutions included
 - wants not to be using JavaScript (let .NET Core Blazor make it for us)
 - Follow the .NET Core features, coding patterns and philosophies
 - Wants to include everything needed to develop an application such as Icons and other things for UI
 - Is Open Source so anyone can download and delete,modify,use,sell,reproduce,call it their own as desired.
 
 I know there is more to Oqtane Framework than just those points that make it attractive to want to help contribute to it as an opensource project.  I just don't want to see it become another "Sell Out"
 
 Again this is a reusable search UI component completely 100% original and tailored for Oqtane Framework I engineered myself for the community.  I would not just include it in the pager but use it with the pager.  This should be separation of concerns logic.  Which is why I would like to move the button logic to its own component.
 
 This also demonstrates a little of where I am as an Oqtane Framework contributing developer resource for the community.  I keep schooling myself day after day on new  topics.  Old saying I was once told is "the more you know, the more there is to know" and boy is that true when it comes to scientific things like engineering software or even using a framework like Oqtane.
 
 My hope is that you can go through it, fine tune it, love on it, maybe if you like I can make the button component and we can separate that concern and start utilizing it.
 
 Wouldnt it be great to have UI components in Oqtane and NOT need a third party?
 
 This is the chance to everyone in Oqtane that develops components to speak up on this topic as this PR has opened this topic up.  Maybe a discussion needs to be created?  Your post on Blazorise changing licensing... I didn't want to use it already.  They all have issues and they all seem to rely on some other stuff like bootstrap, tailwind, material and so on... Oqtane Framework components should be made very "generic" to allow any front end developer to go to town with it.
 
 We have had this discussion since BETA and I have pushed for things like `app-element` instead of `oqtane-element` to keep things generic for security reason and for a very SOLID, KISS, DRY principles.  This is why I am still here ;) or I would of jumped ship a long time ago.
 
 CSS Styling and UI components are important to the Oqtane Framework's success.   You have done a great job listening and bringing things into the framework that make logical sense. 
 
 Yes I am opinionated on this, but I feel we all are.
 
 The idea here is if I create something that needs to display data as a module I want something out of the box I can just port into an app.
 
 Keep this as a component because developers may find this perfect for what they want to use this with a different Pager.
 
 I also separated concerns of logic through the different methods.  I am all for these being re-engineered as needed to make everything function and easy to maintain.
 
 I also wanted to discuss creating another module or two besides just the Blog along with enhancing the blog module.  Personally I don't really care to have a repo and deal with the maintenance of it as of now or I would have a few already.  I would be more willing to team up with someone for the fun of it to see how far we can take something together and with a community.  
 
 As of now I am very invested in a project that took me way underwater spending on development and helping DNN.  I don't even wish to discuss this as I am looking at the now, learning from the past challenges I had trying to make a dream come alive in DNN.  I made a lot of websites, fixed a few things that took YEARS to get anyone to even understand the issue.  I ended up fixing it deep in the code without Visual Studio, testing or anything... I just read the code until I found the issue and I Think it was 2 lines of code modified that made it so emails could be sent properly when testing.  It REALLY bugged me and cost me massive amounts of time troubleshooting my email servers instead of looking into the Framework.

Other issue was the CSS load order, everyone argued with me saying it loaded a certain way.  I proved them wrong because it was hard to get a style consistent with the framework while using vendor modules.

I put up a fix for that but the breaking changes... also fixed the Journal module to actually make links like it used to and was going to doctor that up, showed all the code to fix it but that was the straw that broke the camels back because I fixed it but no one else wanted to contribute to it to add whatever it was needing to make it work.  So many different technologies to study to perform that task as working with the Persona Bar was a bit complex...  Then Blazor came out and I started paying attention to how we can migrate DNN to Oqtane.

The user migration function in the new version cures this for me... thank you again.  For that I wanted to thank you and the community back with something.  I did not notice anything to do as this has a lot already and you are pushing your directions and I want to stay out the way to let you work.  But when another contribution was made for the admin pages pager I started thinking of all the issues I have with these pages and how I can help make components or enhance existing ones.

Well this is my first attempt.  I wish I had spent more time on it but I didnt know and still dont know if it would even get accepted into the framework.  

Again this allows MANY different configurations so using it with a pager or your own table you created should work great just use the options that make like the results the most!

**Comment by thabaum** [comment]
On another note, I have not tested the look of this on Maui yet.  However the css selector is there for any front end developer to make adjustments.  I was going to wait for feedback here first and see what you might want to do with it if anything.  Main concern was some padding or margin to keep it away from the current UI components like the pager and buttons.

**Comment by thabaum** [comment]
As far as adding this control to the Pager control, I see no reason it should not work.  It would be the same as adding button controls to the pager/search and so on...  Something maybe you can explore and fine tune for it if you like.

**Comment by sbwalker** [comment]
@thabaum you touched on a point above which is a fairly widespread misconception when it comes to Blazor development...

Based on the fact that Blazor has a component model, it leads people to believe that everything should be abstracted as an individual component. I have seen this referred to as "micro-componentization" where applications are broken down to the most primitive UI components, and then those components are used withing "macro" components, which are then used within application components, etc...  This all makes sense in theory based on object oriented principles. 

However there is a real performance cost to using so many components, as each component has its own state, events, and its own life cycle. The rendering time for deeply nested component render trees is very expensive. I would encourage every Blazor developer to read this guidance from Microsoft: 

https://learn.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-7.0#avoid-thousands-of-component-instances

And I realize that most of the popular UI component libraries provide micro-components for every possible UI element... and .NET developers like this approach (likely because it is "familiar" to them based on prior desktop or mobile development experiences)... but there are real performance impacts.

The overarching theme for Oqtane is "performance" - therefore Oqtane has tried to avoid micro-components in its Admin UI and has utilized standard HTML markup as much as possible. I believe this provides more context as to why I do not want to introduce primitives like a "button" component. And also why I asked if it would make sense to integrate this into the Pager component rather than include it as a stand-alone component.

**Comment by thabaum** [comment]
@sbwalker thank you, I will let you get some work done ;) something to chew on when you are up to it no worries or hurries, just making a contribution as a thanks for all the hard work you have done and I hope this is worthy of your time.

I will keep further discussion here in this thread, thanks again.

**Comment by thabaum** [comment]
@sbwalker there she is, take her for a spin.

Only issue debouncing with TImer works great but not updating pager results some odd reason.

I would organize the parameters better down the road but overall, you can just set the `Setting.Search.IsEnabled` to `true` in the resource file and you can see it work along with some ideas, the pin stripping, dingle balls, hydraulics... and other fun stuff incorporated into this.

I also included documentation for parameters and methods.

Hope it is worth the drive and you have some fun with the params!

**Comment by thabaum** [comment]
closed with fix #3363

**Comment by thabaum** [comment]
@sbwalker I am always happy to help this project, chew on a bone to get the framework to excel further ever since Beta.  It was a great experience playing with all these ideas I had to implement and I am happy to see it was as useful as it was for input towards a solution that would help other developers down the road create something that is not dependent on any other libraries if they choose to use UI components like the pager from within the framework.  

It is huge for you as the project lead to allow these to be more advanced so developers do not need to rely on other libraries that bring other risks outside of the control of licensing and support issues.  It really minimizes the footprint needed to build out a custom modular application which I seen as a huge benefit that would outweigh the cost of maintaining down the road it in my opinion.  It also ads that much more value here for helping other developers adopt the framework which should also bring even more love in contributions and feedback to help steer the project towards even more success.

The response and dedication you have for this project is unmatched in any other repository I have ever reviewed or worked with.

Again thank you for taking the time to review and implement what would be considered worthy of the Oqtane Modular CMS & Developer Framework.  Most other projects would maybe review and then not do anything further, even if the ideas and feedback were genuine.  This is a quality you bring to the table here and why I am willing to help contribute from the start.  It really makes it fun!  

Its not always easy to communicate via texting and takes time to produce each response which takes getting used to, however it does give time to digest things further on all fronts.  It can be discouraging for most, but I see it as nothing more than challenges to overcome that are worth the risk.  It is easy to misread or overlook a statement which I am guilty of as I take what time I can to put towards a contribution for any project like the Oqtane Framework.   Sometimes it is only very brief amount of time allowed to try to digest thing and patience pays dividends at the same time you try to get things rolling as fast as possible to move on to the next goal. 

Oqtane Framework Version 5 this project will really come alive as people gain the experience working with it more between now and then.  I feel bad I can't keep up with it all like I want to due to so many outside forces from this project in my daily life.

Keep up the good hard work and passionate dedication as the future is so bright here I have to be sure I have my shades on to review all that is new!

**Comment by thabaum** [comment]
@sbwalker i will go through this pager control search feature today as I have not had time to review it.  I am updating my IDE now to work on things this week as I can focus more on Oqtane and a future module I may release potentially next week.  I appreciate all the work I have seen done so far to make this enhancement into the framework by you and @leigh-pointer.  It was a fun one to work with making a component pull all this off :).  I will report any issues and fixes if found by end of today. thank you.

**Pull request closed without merging**
