### PR TITLE
add upgrade support for language packages

### PR DESCRIPTION
**Pull request by sbwalker**

### CODE REVIEW

**Comment by sbwalker** [comment]
@hishamco @leigh-pointer what would the package name be for a specific Nuget language package for the Oqtane framework? Would it be Oqtane.Client.{culture}.{version}.nupkg? Will there ever be a need to localize items in Oqtane.Server or other projects shipped as part of Oqtane... and if so should the language package be named Oqtane.Framework.{culture}.{version}.nupkg so that it could contain multiple satellite assemblies?

**Comment by hishamco** [comment]
`Oqtane.Client.{culture}.nupkg` for Oqtane client resources no need to specify the version while NuGet is already taking care about the versioning

**Comment by leigh-pointer** [comment]
@sbwalker this sounds good to me.

**Comment by sbwalker** [comment]
@hishamco - so you are saying that there will never be any resources for the Oqtane framework other than those on the Oqtane.Client project? I am not so sure about this - which is why I asked the question.

**Comment by hishamco** [comment]
> so you are saying that there will never be any resources for the Oqtane framework other than those on the Oqtane.Client project?

May be there will be resources in other projects, if you remember I moved the shared resources to `Oqtane.Client` to make it easier but in can youu want me to make this happen I can move the shared resources to Shared project so that will prove all the resources are working fine

**Comment by hishamco** [comment]
Regarding to the resources we can start test the newly added feature by generating a NuGet packages for `Oqtane.Translations`, 

@leigh-pointer hope you already test this?

**Comment by sbwalker** [comment]
I dont think anything needs to be moved now... I am trying to anticipate future scenarios and make sure the decisions we make now will support those scenarios. I think the safe assumption is that there may be multiple satellite assemblies needed in the future to localize the framework. So the language package name should not be directly associated to a specific assembly - it should be more generic. Oqtane.Framework.{culture} makes the most sense.

**Comment by hishamco** [comment]
> I think the safe assumption is that there may be multiple satellite assemblies needed in the future to localize the framework

Exactly

> Oqtane.Framework.{culture} makes the most sense.

LGTM

**Comment by sbwalker** [comment]
In regards to Oqtane.Translations it would be best to create a language package for each culture/version - not a single language package for all cultures, as we do not want to force people to install resources that they do not require.

**Comment by hishamco** [comment]
Exactly, but we could have a notion of `Oqtane.Framework.all` to include all the supported translations if someone interested rather than download indivisual package

**Comment by sbwalker** [comment]
true... but it would not be supported through the Language Management UI. The Language Management UI displays whether or not a framework language package exists for a specific culture on Nuget.org.

**Comment by hishamco** [comment]
I didn't test the added feature, but I give it a try when I have some time

**Pull request merged**
