### PR TITLE
Fix for #4168 #4170 missing Translations

### PR DESCRIPTION
**Pull request by leigh-pointer**
Resx entry for Module Settings Permissions tab

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer does this resolve all of the "[BUG] Translation failure" issues which were logged by @marceloatoledo in the Issue tracker?

**Comment by leigh-pointer** [comment]
@sbwalker, 
Yes.  I would leave this open for a bit as @marceloatoledo seems to be weeding out a lot of them.

**Comment by sbwalker** [comment]
@leigh-pointer I already merged this PR. But I need to know which Issues can be closed.

**Comment by leigh-pointer** [comment]
@sbwalker all of his can be closed.

**Pull request merged**
