### PR TITLE
Prevent deleting master tenant

### LINKED ISSUE #317: Why there's ability to delete master database

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #317

### CODE REVIEW

**Comment by sbwalker** [comment]
The fix handles the UI but it also needs to be handled in the API as you do not want the master tenant to be deleted via an API call.

**Comment by hishamco** [comment]
I forgot that ;) I will update it soon ..

**Comment by hishamco** [comment]
Done!!

**Comment by sbwalker** [comment]
after further review, this change does not really accomplish the goal. The "master" tenant is very important because it is the registry which is used to access any of the other tenants. If you consider a scenario where someone installs Oqtane and then adds an additional tenant "Tenant2", you code you added would not prevent them from deleting the "master" tenant ( as the number of tenants > 1 ). It would seem that we need a bit flag on a Tenant for IsMaster which can be checked, or we need to use a constant for the name of the master tenant which can be used for verification.

**Comment by hishamco** [comment]
> this change does not really accomplish the goal

You 're right, let me have a look again ...

**Comment by hishamco** [comment]
@sbwalker could please check it again

**Pull request merged**
