### PR TITLE
IDeletable implementation for Page

### PR DESCRIPTION
**Pull request by fileman**

### CODE REVIEW

**Comment by fileman** [comment]
In Delete.razor, PermissionGrid should be:
1. removed;
2. readonly add a div with style="pointer-events: none; backgroud-color: same_color_of_disabled";

**Comment by sbwalker** [comment]
Good question. I think the permission grid should probably be removed from the Delete component, as it does not really serve any useful purpose.

**Comment by fileman** [comment]
After changing IsDeleted value, I've to reload from browser to hide/show page from menu, there is a method to reload the Menu.razor component or we need it?

**Comment by sbwalker** [comment]
I think the problem might be that the Menu component is currently using the OnInitialized event rather than the OnParametersSet event. You can try changing it and test to see if it resolves the problem.

**Comment by fileman** [comment]
You are right, changed in #104

**Pull request merged**
