### PR TITLE
UserProfile View (Notifications View): Resolves issues with enabled/disabled input along with viewing or replying to notifications

### LINKED ISSUE #539: User Profile: Viewing Notification Messages Allows Editing
The fields in View Notification (messages) allow changing and editing,

### PR DESCRIPTION
**Pull request by thabaum**
fixes #539 

DO NOT MERGE THIS PR AS IT IS DIVIDED IN TWO.

https://github.com/oqtane/oqtane.framework/pull/585  UserProfile\Index
https://github.com/oqtane/oqtane.framework/pull/586  UserProfile\View

## **The ABOVE two PR's Issues fixed**

Index:

- Infinite RE: in reply messages
- Adds "..." to messages longer than 100 characters in the profile notifications view
- Removes carriage returns from message
- Removed reply message from user profile notifications tab messages

View:
- Reply Message Page Break using underscores
- Ability to enter cursor into reply area without having to hit enter to type message
- Enabled/Disabled input depending on view or reply
- Original Message shows up in text box that allows scrolling and line breaks.

## Screenshots

_Edited_
- Easier to put cursor at top of message text area with previous message adding line breaks to the body
image

- Fixes infinite subject RE: RE: RE:....
image

- Original message displayed in same format to display properly (although something else is bugging out the layout of the table possibly in the buttons)
image

- Removes fields you do not need to see when sending a reply
image
(date is not showing, but is added to the reply message.)

- Enables/Disables fields while viewing notifications and replying as necessary
image
image

image

This PR also now detects and removes the reply message from the User Profile Notifications message and adds a "..." to the end of the message if > 100

image

### CODE REVIEW

**Comment by sbwalker** [comment]
There are problems with this PR - it breaks the ability to Reply to notification as the Message field is flagged as ReadOnly.

**Comment by thabaum** [comment]
OK Thanks for finding that I will fix that issue.

**Comment by thabaum** [comment]
> 
> 
> There are problems with this PR - it breaks the ability to Reply to notification as the Message field is flagged as ReadOnly.

Sounds like an "If" statement or a new form for "reply" needs to be created...  what do you think?

**Comment by sbwalker** [comment]
since the component already supports the ability to reply I would think that an @if (title == "To") statement around the message field would be the best approach.

**Comment by thabaum** [comment]
so my "if"y idea I edited out was correct answer :)

What if the reply button puts a new form text area on the same form, then a send button?

This way we can enhance the messages, and view them while we reply.

**Comment by sbwalker** [comment]
You can already view the message while you reply - it displays the original message beneath the text box when you are replying.

**Comment by thabaum** [comment]
Gotcha, I will take a closer look unless you can make a quick edit.  I think the if statement is choice.

**Comment by thabaum** [comment]
Please test out this file on your local... I think it should be heading in the right direction for a quick adjustment to things.

I added some stuff maybe we dont need... however in the profile notifications area where it shows the first line of the message I have a fix for that area in mind I think would be slick ;)

**Comment by thabaum** [comment]
image

image

**Comment by thabaum** [comment]
Other issues fixed...

- no longer goes RE: RE: RE:....
-  Original message you can see where it would be and only displays for reply
- Removes fields you do not need to see when sending a reply
-  Keeps a dialog of the conversation in the message similar to email  (can make this optional possibly?! or remove... or just keep it as is!).

**Comment by thabaum** [comment]
@sbwalker I edited the issue description to better explain what issues this PR currently is trying to address.

I will add screenshots as well soon to help explain.

**Comment by thabaum** [comment]
If you think what I have done can work, the other issue we should address is possibly the way the one line of message is showing missing line breaks.

image

I am thinking a textbox 1 row that you can scroll each message line by line if you like for a quick way to access a lot of messages fast using same amount of the UI to give this UX.

**Comment by thabaum** [comment]
I went ahead added the tweaks in for making things work with viewing notifications list in the framework.

image

image

**Comment by sbwalker** [comment]
I was trying to model the default Notifications view after Gmail or Outlook where there is a preview of the message displayed in a single line.

image

**Comment by sbwalker** [comment]
Desktop view:

image

**Comment by sbwalker** [comment]
Desktop view...

image

**Comment by thabaum** [comment]
Gotcha

**Comment by thabaum** [comment]
I think it would be easier with DIV containers than using a table, what do you think?

**Comment by thabaum** [comment]
That must be Gmail screenshot because Outlook is a bit different.

Whatever is clever...  I think it would be fun to make a UI similar to those.  

You probably have an idea how to make all this happen just been waiting to do it, I don't want to step on anyone's toes here, but I will see if I can create something more like the Gmail responsive view you shared.  Although if we had the Blazor original theme layout we could make it more like Outlook.com for desktop with trash, saved items, deleted, junk and ability to create folders to help manage messages.

But then a complete UX rewrite in a way... for what is currently v1 I propose a regex or way to add three dots to the end of the line if longer than so many characters prior to any dashes or some combination of characters for the message breaks to allow keeping the conversation going in each message.

On another thing if I am way off here... is to just take what you like from my PR's and add them as you wish.

Your wish is my command, master.

**Comment by sbwalker** [comment]
It a bit difficult to reconcile the discussion and code changes in this PR - but I am assuming this PR is not ready to be merged, correct?

**Comment by thabaum** [comment]
Not ready just yet.  I am going to work on the view page one more time.  I almost have the solution ready to be acceptable to allow merging the PR with desired results as discussed.

I will give this a go tonight/tomorrow should be done.

**Comment by thabaum** [comment]
ready to rock however it looks like I need to add those other changes or can you make the conflicts go away?

**Comment by thabaum** [comment]
are you still able to merge this PR with conflicting files or should I redo my PR files with the newer changed files is my question.  I am confident this is good to go if things are ok it should get us by for now as far as some basic functionality goes.

**Comment by thabaum** [comment]
Made one more quick change to the length of the --------------------------------------------

I will edit the PR at the top to fully disclose changes here.

**Comment by thabaum** [comment]
hoping i did the conflict changes right.

**Comment by thabaum** [comment]
something does not feel right, Things are not formatting correctly and I am getting weird errors is VS when looking at the file, or even the current source file when looking at it in my project.  I think I need to rebase things.

I may just create a new PR.

On top of all that my Visual Studio needed a patch so maybe that will cure something...  I will try to have this done up in the next hour @sbwalker

**Comment by thabaum** [comment]
I broke this down into two PR's

Trying to get my changes to keep up with framework I think is a challenge along with keeping VS updated so things format right.

You can test each one individually as they are fairly straight forward fixes, I spend more time doing the PR...

**Comment by thabaum** [comment]
I referenced this issue in the other two PR's and separated the conversation a bit to allow changes to each page section if needed individually so I cam going to go ahead and close this PR tomorrow if you don't.

**Comment by thabaum** [comment]
Use 
#586
and
#585

**Pull request closed without merging**
