### PR TITLE
Packages update to 3.1.2

### PR DESCRIPTION
**Pull request by chlupac**

### CODE REVIEW

**Comment by sbwalker** [comment]
This PR upgrades Oqtane to Blazor 3.2 Preview 2 which is not an officially supported release yet. In order to release the Oqtane MVP, it needs to be on an officially released version of Blazor. So I cannot accept this PR.

**Comment by aubrey-b** [comment]
How about creating a dev branch that has the latest bits? Preview 3 dropped today.

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/

**Comment by sbwalker** [comment]
After talking to a number of people in the past couple weeks who are close to Blazor, I have been thinking a lot about this topic. The general feeling is that although server-side Blazor is a very capable technology, it is client-side Blazor which is going to be the real game-changer. This is because it is client-side Blazor which truly provides a viable alternative to all of the JavaScript SPA frameworks for building enterprise web applications - and it also provides a viable solution for mobile applications.  The goal for Oqtane from the very beginning was to support both hosting models, and the current architecture has been proven capable in achieving that goal. That being said, there are currently a lot of changes happening in client-side Blazor, and Dan Roth urged me to keep up with the latest bits to ensure Oqtane maintains its support and is ready for the release. So I am contemplating the idea of aligning the client-side Blazor release date in May with the MVP release date for Oqtane. This would ensure that the product is fully ready for the opportunity... and it provides some to release public Beta versions leading up to the release. I will post this in the Gitter channel to solicit some feedback.

**Comment by sbwalker** [comment]
@chlupac do you want to make the changes to upgrade to .NET Core 3.2,0 Preview 3?

**Comment by chlupac** [comment]
@sbwalker Sorry, I will probably be busy the next few days and I can't promise to do it.

**Comment by sbwalker** [comment]
No worries, I can take care of it

**Pull request closed without merging**
