### PR TITLE
Page editor fix & Script check

### PR DESCRIPTION
**Pull request by chlupac**

### CODE REVIEW

**Comment by sbwalker** [comment]
Themes are not required for pages. You need to be able to leave them unassigned so that they inherit the theme from the site.

**Comment by chlupac** [comment]
Yes I know. but current version complains about it and do not let me save. 
This PR fixed it.

**Comment by sbwalker** [comment]
But it is not the correct fix. Do you want me to take a look or do you want to?

**Comment by sbwalker** [comment]
My apologies. I now see what you corrected - I was not reading this correctly. Thank you for fixing this.

**Pull request merged**
