### PR TITLE
Add password complexity requirements message to password Reset module.

### PR DESCRIPTION
**Pull request by W6HBR**
This adds the same functionality that already exists in the UserProfile module.
@microsoft-github-policy-service agree

### CODE REVIEW

**Review by W6HBR — COMMENTED** [review]
@dotnet-github-policy-service agree

**Comment by W6HBR** [comment]
@microsoft-github-policy-service agree

**Comment by sbwalker** [comment]
@W6HBR can you please accept the CLA so that I can merge this PR

**Comment by W6HBR** [comment]
@sbwalker Do you have a link to where I can do that?  

The links I found to do it at the DOTNET Foundation are dead and all other links I find discuss setting it up from a project side.  The link included above from the automated check links to setting up the service, not accepting the agreement.  However, within that page it does include a note that says to include a comment with the line `@microsoft-github-policy-service agree`, which I have done, but does not appear to be enough.  https://github.com/microsoft/contributorlicenseagreement#accepting

**Comment by sbwalker** [comment]
@W6HBR I will escalate to the .NET Foundation

**Comment by ChrisSfanos** [comment]
Hi @W6HBR - Oqtane is a .NET Foundation and not a Microsoft project.  I'll have to look for the specific line, but it should be something like @dotnet-github-policy-service (instead of @microsoft-github...)

**Comment by W6HBR** [comment]
@dotnet-policy-service agree

**Comment by sbwalker** [comment]
@ChrisSfanos  Thank you Chris!

**Pull request merged**
