### PR TITLE
Fix regression bugs

### LINKED ISSUE #330: DefaultLayoutType value is "string.Empty"
I know there was some refactoring done, so now in Client/Modules/Admin/Sites/Add.razor when the layout type is null the DefaultLayoutType contains the value "string.Empty". Was this the desired result?

add-site

When adding a new site with the Blazor theme and no default layout I get this error.

chul1

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #330 which is address `string.Empty` regression bugs that was occurs from #314

### CODE REVIEW

**Comment by hishamco** [comment]
I think `@string.Empty` will render `value=` while the intend to render `value=""`, `@string.Empty` is useful in C# code not in HTML unless there's a proper places

Am I right?

**Comment by chlupac** [comment]
you have to use "@string.Empty"

**Comment by sbwalker** [comment]
I explained it in my post on #330 - adding the @ symbol works fine, I tested it.

<option value=@string.Empty>&lt;Select Layout&gt;</option>

**Comment by sbwalker** [comment]
Actually I am not sure how much value there is in using @string.Empty over "" in razor components. This is markup which is going to the browser and executing code to produce "" seems like overkill.

**Pull request merged**
