### PR TITLE
Quill Security related bug fixes.

### PR DESCRIPTION
**Pull request by leigh-pointer**
Upgraded Quill references to 1.3.7
Tabnabbing vulnerability in snow theme #2438
https://github.com/quilljs/quill/issues/2438

https://github.com/quilljs/quill/releases/tag/v1.3.7

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer is there a reason why the quill 1.3.6 JS and CSS files were not removed from the wwwroot folders?

**Comment by leigh-pointer** [comment]
No, i must have missed that, sorry!

**Comment by sbwalker** [comment]
@leigh-pointer no worries.... I removed them now

**Comment by sbwalker** [comment]
@leigh-pointer I know this was contributed quite some time ago... but do you have any context on why you felt we needed to upgrade Quill to 1.3.7... and once Quill was upgraded, did you experience any issues - specifically were you still able to insert images using the rich text editor component in Oqtane? I am investigating #2252 and I can reproduce the problem locally however I am not sure how long this issue may have existed. It is possible that it was introduced in the upgraded to 1.3.7 so I was going to test a rollback to 1.3.6 but if there is a reason why we should not use 1.3.6 then I need the context.

**Comment by sbwalker** [comment]
@leigh-pointer I am guessing that the Delta feature (which image insertion relies upon) may have been moved to a separate library https://quilljs.com/docs/delta/ in version 1.3.7?

**Comment by leigh-pointer** [comment]
Some work needs to be done i guess!
Will try to sort it this weekend.

**Pull request merged**
