### PR TITLE
Fix Permissions on Pages and Modules #1271

### PR DESCRIPTION
**Pull request by leigh-pointer**

### CODE REVIEW

**Comment by sbwalker** [comment]
@leigh-pointer this does not follow the guidance I provided in #1271. The module View permissions should be set to the Page Edit permissions. Consider a site with a custom role of "Editor" and a page provides Edit permissions to the "Editor" role and View permissions to "All Users". A user is logged in who is a member of the "Editor" role. When this user adds a new module to the page, the module should have "Editor" permissions by default - as if the module was only given Edit permissions to "Administrators" ( as in this PR ) then the user would be prevented from editing the module.

**Comment by sbwalker** [comment]
Simply use UserSecurity.GetPermissionStrings(PageState.Page.Permissions) to get a List<PermissionStrings> and then remove the item with a PermissionName of PermissionNames.View and then use UserSecurity.SetPermissionStrings() to recreate the string.

**Comment by leigh-pointer** [comment]
@sbwalker  Just doing that now!

**Comment by leigh-pointer** [comment]
PR Permissions for edit are applied from the page permissions. #1301

**Pull request closed without merging**
