### PR TITLE
ControlPanel move page's code into OnParameterSet

### PR DESCRIPTION
**Pull request by fileman**

### CODE REVIEW

**Comment by sbwalker** [comment]
I cannot merge this as it includes an appsettings.json file

**Comment by sbwalker** [comment]
I made the necessary in a new pull request

**Comment by fileman** [comment]
> I cannot merge this as it includes an appsettings.json file

I see in .gitignore the Oqtane.Server/appsettings.json, but is also tracked in project so it isn't ignored, can be excluded from project so .gitignore will work?

**Comment by fileman** [comment]
ignore previous comment, I have solved with git update-index --assume-unchanged Oqtane.Server\appsettings.json

**Pull request closed without merging**
