### PR TITLE
Remove admin border after edit

### PR DESCRIPTION
**Pull request by erw13n**
After finish Edit, there's a class "container" which is conflict with Bootstrap that cause an issue on Full-width pane.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=1188) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=1188) before we can accept your contribution.<br/><br/>:x: erw13n [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=1188)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.framework?pullRequest=1188) it.</sub>

**Comment by hishamco** [comment]
Could you please share a GIF to see the UI issue on action?

**Comment by erw13n** [comment]
Indeed, we can just overwrite the CSS. 
But I would suggest to set _useadminborder to false instead of changing the CSS class.

**Comment by sbwalker** [comment]
I will have to take a closer look at this as I am concerned that this change will have an adverse effect on themes which do not use full-width panes.

**Comment by sbwalker** [comment]
After further testing I think your fix is in fact the correct solution. Thank you for sharing!

**Pull request merged**
