### PR TITLE
remove Microsoft.AspNetCore.Localization

### PR DESCRIPTION
**Pull request by sbwalker**

### CODE REVIEW

**Comment by sbwalker** [comment]
note this PR adds Microsoft.AspNetCore.Http which will need to be removed in a subsequent PR

**Comment by hishamco** [comment]
Is there a reason to remove it?

**Comment by sbwalker** [comment]
@hishamco Microsoft.AspNetCore.Localization version 2.2.0 has been flagged as deprecated for quite some time (https://github.com/dotnet/announcements/issues/217). In .NET 9 it is now flagged as containing a critical severity vulnerability:

```
warning NU1904: Package 'System.Text.Encodings.Web' 4.5.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28
```

**Comment by sbwalker** [comment]
@hishamco Microsoft.AspNetCore.Http also contains System.Text.Encodings.Web as well so it has a similar problem in the upgrade to .NET. You can read more about it here: https://github.com/dotnet/aspnetcore/issues/58593

**Comment by sbwalker** [comment]
@hishamco please read: https://github.com/dotnet/aspnetcore/issues/58593 - it is not possible to access Microsoft.AspNetCore.App from within a Blazor Client project (ie. ```<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">```). CookieRequestCultureProvider is only available in Microsoft.AspNetCore.App

**Comment by hishamco** [comment]
Maybe I didn't dig into the latest link, so can we add `Oqtane.Localization` project or namespace for that to make things much cleaner and organized

> This is a major headache in upgrading to .NET 9.

Good to know that

**Comment by sbwalker** [comment]
"can we add Oqtane.Localization project or namespace" I would prefer not to at this time as I am still exploring various solutions to try to avoid copying these classes into Oqtane

**Comment by hishamco** [comment]
Do you want me to try something?

**Pull request merged**
