### PR TITLE
Improved recycle bin

### PR DESCRIPTION
**Pull request by fileman**
this should complete the #105 with the expected behavior

### CODE REVIEW

**Comment by sbwalker** [comment]
Thank you for the PR... a few comments:

- currently the /controls folder is intended for generic components which are applicable for use in any module. The TabControl and TabPage components do appear to be generic so this seems like a good approach.
- So far the user experience for Oqtane does not utilize any Tabs however it makes sense in scenarios where there are a lot of options to represent in a component that it would be useful to organize/group them. 
- Oqtane already has an entity named "Page" and it creates confusion if the "Page" term is used for other purposes. Another suitable alternative in this case may be "TabPanel"?
- Oqtane relies on Bootstrap 4 for its global styles. By utilizing such a widely used style system it makes the product much simpler for designers and developers. However, this also means that the product should implement the Bootstrap standards as closely as possible and not introduce custom options when a suitable Bootstrap option already exists. In this regard it would make sense for the generic Tab to be based on the Bootstrap Tabs nav https://getbootstrap.com/docs/4.0/components/navs/#tabs ( with perhaps a Parameter so that a custom class could be substituted - "nav-tabs" or "nav-pills" )

**Comment by fileman** [comment]
I've tried with bootstrap nav-tabs, but without success, they are not rendered even if the elements are present in DOM.
I've added Tab* controls as a workaround to show the result of recyclebin behavior, if it is ok I'll try to use only bootstrap.

**Comment by sbwalker** [comment]
Sorry... the problem is that Bootstrap tabs relies on another JavaScript plugin https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior .- I thought it only depended on jQuery. So... we have a dilemma... add another JavaScript reference, or create a Blazor native Tab control...

**Comment by sbwalker** [comment]
In general my opinion is to use native Blazor functionality rather than JavaScript when possible as this is one of the big advantages of Blazor.

**Comment by sbwalker** [comment]
So perhaps just rename TabPage to TabPanel

**Comment by fileman** [comment]
I've experimented RecycleBin with bootstrap card ... I don't like it very much, but if you want I can submit a new PR to show the result

**Comment by fileman** [comment]
You can find it [here](https://github.com/fileman/oqtane.framework/tree/RecycleBinWithBootstrap)

**Comment by sbwalker** [comment]
I moved the controls to the Modules/Controls folder as these components are intended to be used in Modules - not Themes.

**Pull request merged**
