### PR TITLE
Some methods failing in BaseEntityBuilder if Schema is not null.

### PR DESCRIPTION
**Pull request by dkoeder**
Some methods failing in BaseEntityBuilder if Schema is not null.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=2356) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=2356) before we can accept your contribution.<br/><br/>:x: dkoeder [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=2356)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.framework?pullRequest=2356) it.</sub>

**Comment by sbwalker** [comment]
@dkoeder with all of these changes to support schemas, would it also make sense to enhance the SQL Server config component to allow a user to provide a schema name? Them it would be possible for the installation Wizard to support schemas.

**Comment by dkoeder** [comment]
Currently the projects I am working on are fine with the main Oqtane tables being on the default schema. But I would love to hear some thoughts on the advantages of this being supported.

**Comment by sbwalker** [comment]
@dkoeder I did some initial research into this and it appears to be a non-trivial effort - and since nobody is asking for it, I would have to prioritize it much lower than other enhancements.

**Pull request merged**
