### PR TITLE
Fix Azure deploy

### PR DESCRIPTION
**Pull request by jimspillane**
Fixes Deploy to Azure Button in #959 

FYI- this is on the Master branch.

### CODE REVIEW

**Comment by hishamco** [comment]
Why it's on the master?!!

**Comment by sbwalker** [comment]
@hishamco this is on master because it fixes a breaking issue in the 2.0.0 release and we would want to include it in a 2.0.1 release. The fix should also be propogated to the dev branch as well.

**Comment by jimspillane** [comment]
> The fix should also be propogated to the dev branch as well.

@sbwalker I will submit the PR to dev after I check the strange behavior @ADefWebserver observed in his test https://github.com/oqtane/oqtane.framework/issues/959#issuecomment-738957362

**Comment by ADefWebserver** [comment]
> @sbwalker I will submit the PR to dev after I check the strange behavior @ADefWebserver observed in his test [#959 (comment)](https://github.com/oqtane/oqtane.framework/issues/959#issuecomment-738957362)

@jimspillane - I really think that it was just an Azure timing-out issue (because Oqtane is so big it takes a long time to pull the code from GitHub and compile it). Your PR definitely fixes the error that I had. Good Job 👍🏾

**Comment by jimspillane** [comment]
Thanks, @ADefWebserver let me know if it happens again, and I will investigate.

**Pull request merged**
