### PR TITLE
Added Sorting to User- could be extended to other Pagers.

### PR DESCRIPTION
**Pull request by leigh-pointer**
Added the ability to sort the Pager data by clicking the Pager Heder Column.

Oqtane-PagerSorting

### CODE REVIEW

**Comment by leigh-pointer** [comment]
Updated Recycle Bin with column Sorting

**Comment by sbwalker** [comment]
I have not merged this PR for a number of reasons. From a business perspective, sorting can be a useful feature for users when dealing with certain types of data (ie. amounts, etc...), however as a general feature for the types of information managed in the Admin UI I am not sure it is very useful. From a technical perspective I have concerns on how it would scale with higher volume and I do not like how much duplicate/custom code needs to be added (and maintained) in each razor component to support it. Overall, the main question is related to the amount of value it adds to the product.

**Comment by leigh-pointer** [comment]
@sbwalker I have now been running sort on one of my modules with over 25 column and 2500 records.  The performance is unnoticeable.  However I would want to update the Oqtane PR.

**Comment by leigh-pointer** [comment]
I will need to do some refactoring but really happy to do it.

**Comment by leigh-pointer** [comment]
replaced with #3016

**Pull request closed without merging**
