### PR TITLE
Localize log messages

### LINKED ISSUE #933: Localize Logs Messages
We should localize the static logs, coz the dynamics logs are tricky but we could may find a good solution to localize them

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #933

### CODE REVIEW

**Comment by hishamco** [comment]
Log

This is how the added role appear in Arabic

**Comment by hishamco** [comment]
I added `Resources` folder so anyone after can add the resources without creating that folder

**Comment by sbwalker** [comment]
Can you please explain why you needed to add the Root Namespace? It seems unrelated to this Logging enhancement. And it did not seem to be necessary for the foundational localization enhancements you add in 2.0.0.

**Comment by hishamco** [comment]
> why you needed to add the Root Namespace

This because you change the rootnamesapce in `Oqtane.Server.csproj`

```
<RootNamespace>Oqtane</RootNamespace>
```

**Comment by hishamco** [comment]
I already add it to `Oqtane.Client` but seems I miss it for `Oqtane.Server`, if you remember that is why I asked to change the Module Creator too to avoid adding this attribute

**Pull request merged**
