### PR TITLE
Notification Repository Breaking change fix

### PR DESCRIPTION
**Pull request by chlupac**
I wondered why my users complains than messages had not been delivered.

### CODE REVIEW

**Comment by sbwalker** [comment]
I integrated a PR enhancement #625 but it appears that it affected existing system behavior. Noting @mikecasas so that he is aware as he created the PR.

**Comment by sbwalker** [comment]
@chlupac did this affect all notifications or just items created prior to the PR being integrated?

**Comment by chlupac** [comment]
All notifications which not fill SendOn field. My system stop to send custom forgot password messages. Corrected now.

**Comment by sbwalker** [comment]
Sorry... I should have caught this, as you are correct that any custom app that was using the Notification API would not have implemented the new property - so it would have been null - and the system should have handled this use case.

**Comment by chlupac** [comment]
No problem, my complains department solved this quickly :) Mike was trying to correct this bug, but on wrong place.

**Comment by mikecasas** [comment]
Wouldn't the sql update statement have fixed this? Should I have declared the property in the db as non null?

**Comment by chlupac** [comment]
@mikecasas  no Sql do not fixed it, it requires change in existing code, because when notification is created, field is not filled.  
But for case when I want to send message immediately, null is ok. It's fixed now, no further changes required.

**Pull request merged**
