### PR TITLE
Fix naming conventions for private fields

### PR DESCRIPTION
**Pull request by hishamco**
Fixes a part of #245

### CODE REVIEW

**Comment by chlupac** [comment]
Nice, I like it.

**Comment by sbwalker** [comment]
This is excellent! The one question I have... and it may be more of a personal preference topic... but I am curious for your feedback on how constructors should be written. Specifically, the use of "this." in the original code was to differentiate between local variables and constructor parameters with the same name. For example, the use of "this." in the code below does not seem to be required if we embrace the coding standard of using "_" on local variables.

        public AliasService(HttpClient http, SiteState sitestate, NavigationManager NavigationManager)
        {
            this.http = http;
            this.sitestate = sitestate;
            this.NavigationManager = NavigationManager;
            this._http = http;
            this._siteState = sitestate;
            this._navigationManager = NavigationManager;
        }

**Comment by hishamco** [comment]
I planned to remove `this` before you ask ;) also using camelCasing for params, this is common on ASP.NET Core repos which I'm participating into

**Comment by hishamco** [comment]
Please don't merge until I finish this today

**Comment by sbwalker** [comment]
I will wait until you confirm you are finished

**Comment by hishamco** [comment]
@sbwalker please :shipit: after the build is pass

**Comment by sbwalker** [comment]
@hishamco you are saying this is ready to be merged?

**Comment by chlupac** [comment]
@sbwalker yes under this stupid icon is ship it

**Comment by sbwalker** [comment]
thank you @hishamco for your efforts!

**Pull request merged**
