### PR TITLE
Blazor WebAssembly localization test

### PR DESCRIPTION
**Pull request by hishamco**
@sbwalker please try this PR to your end to make sure that localization is work at your end

Please add Arabic, French and Spanish languages to your browser and try to switch between then while the application is running, hit a refresh after each change and you should see "Hello Oqtane" on  every culture

### CODE REVIEW

**Comment by hishamco** [comment]
After it works with you can basically change the runtime to  "Server" and set the browser culture to the default culture that has been set in `appsettings.json` then run the app

Please let me know if you face any issue or something is not work

**Comment by hishamco** [comment]
@sbwalker did you test this PR? Don't forget to close it after you ensure if the localization is working at your side

**Comment by hishamco** [comment]
@sbwalker seems this take so long, if the localization is already worked for you, I will close this PR

**Comment by sbwalker** [comment]
I will do some localization testing today. I was hoping others in the community would also assist with localization but so far nobody has volunteered

**Comment by hishamco** [comment]
No problem Shaun I can handle all the localization stuff as much as I can ;)

**Pull request closed without merging**
