### PR TITLE
Fixes #2627 #2631 #2630 #2629 #2632  #2635 - Dev Branch Module and Theme Template Issues

### LINKED ISSUE #2627: Dev - Extra { } in module template
https://github.com/oqtane/oqtane.framework/blob/177632eee02e44686557e7f983b751e119087dcf/Oqtane.Server/wwwroot/Modules/Templates/External/Server/Repository/%5BModule%5DContext.cs#L14

There is an extra { } keeping the build process from finalizing first run.

PR being created...

### LINKED ISSUE #2629: Dev - Module Template uses static location for Oqtane.Server folder location
Module Template uses static location for Oqtane.Server folder location causing problems if you use a different location other than default for Oqtane.Framework such as 'Oqtane.Framework-Dev'

### LINKED ISSUE #2630: Dev - Theme Template uses static location for Oqtane.Server folder location
Theme template folder location defaults to static location.  This can cause unnecessary out of the box errors for a developer new to Oqtane that uses a different folder such as Oqtane.Framework-Dev folder from the developer zip.

### LINKED ISSUE #2631: Dev - Module Template Oqtane.Server [Module]Manager.cs Missing Oqtane.Repository
Missing a using directive for Oqtane.Repository in order to build project.

### LINKED ISSUE #2632: Dev - Theme Control Panel Bugged navbar
Default starter template for creating a theme has a bugged navbar

image

### LINKED ISSUE #2635: Dev - Unable to see toggle menu icon for module actions with default theme creator template
Unable to see toggle menu icon for module actions with default theme creator template.

Issue is with color, I will submit a PR that removes color so it can be set only if needed.  Default theme has white background so it should go with the text color... regardless.

### PR DESCRIPTION
**Pull request by thabaum**
Dev Branch Module and Theme Template Build Fix
Fixes #2627
Fixes #2631
Fixes #2630
Fixes #2629
Fixes #2632
Fixes #2635

### CODE REVIEW

**Comment by thabaum** [comment]
Fixed all issues I found while testing out creating a module with Oqtane.Framework-Dev branch.  Do I need to make any of these for Master or is it ok just to push them out to dev branch?  Dev branch is new but what I was going to use to test some stuff out for fun...

**Comment by thabaum** [comment]
These commits fixed all issues I found that caused bugs while using Dev branch to create modules and themes from within the Oqtane Framework.

**Comment by thabaum** [comment]
I can add the localization to the template as well, maybe a bit more to it than what is here so I want to let this PR since it is most important to push through.   Then I will work on the next patch with the theme settings and resource files if desired for the default theme template creator.

**Comment by sbwalker** [comment]
I am going to merge this PR as the majority of the items it contains are valid - however I do not believe the CSS modifications to the Theme template are valid so I will likely override them with a subsequent PR. In general it is best practice to not bundle many  unrelated modifications in a PR as it makes them much more difficult to review and merge - which means they are more likely to be rejected.

**Pull request merged**
