### PR TITLE
Fix Error with Footer on Oqtane Theme #1282

### PR DESCRIPTION
**Pull request by leigh-pointer**
Added clear div only when the option is selected

### CODE REVIEW

**Comment by hishamco** [comment]
Note: Again I see a lot of commits for a simple change

**Comment by leigh-pointer** [comment]
>  Did you try it in Mobile or Tablet screens?
yes. tested with the google browser device toolbar.

**Comment by hishamco** [comment]
Just squash the commits if it's possible or start a new PR wth single commit

Thanks

**Comment by hishamco** [comment]
@sbwalker I think we need a code guidance to avoid submitting unnecessary commits into any PR, this is a reminder for us to make the review process easy

**Pull request merged**
