### PR TITLE
Use string Interpolation for constructing Urls

### LINKED ISSUE #300: Use C# String Interpolation for constructing Urls
This is an improvement suggestion. For a cleaner code I suggest how the urls are constructed in the Client project services can improved by using interpolation or string.format.

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #300

### CODE REVIEW

**Comment by sbwalker** [comment]
Looks good!

**Comment by mikecasas** [comment]
@sbwalker Going forward as a pattern should we use string interpolation? Also if we see string concatination do you want PRs to fix?

**Comment by sbwalker** [comment]
I think string interpolation is a good practice going forward. As far as refactoring existing cases of string concatenation I think we need to limit the modification of code/functionality which is already working or else we will spend all of our time dealing with regression and never get to a 1.0 release.

**Comment by hishamco** [comment]
But there are few cases may it need improvement to make code cleaner and readable .. please check my PRs

**Comment by sbwalker** [comment]
Indeed there is always room for improvement - however “clean” and “readable” are subjective concepts based on individual developer preference. What I was saying is that we need to focus on stability at this stage rather than refactoring code that is already working.

**Comment by hishamco** [comment]
Sound good nothing but, we can do improvements if it's possible, because we can't break APIs if we shipped `1.0.0` until `2.0.0`. IMHO we can plan about `RC` before `1.0.0`, so we will have enough time for test-ability and stability before GA

**Pull request merged**
