### PR TITLE
Nav Element "controls-group" class styling - Fixes #3760, #3762

### LINKED ISSUE #3760: BUG: 5.0.3 Login control is not displayed inline
## Issue
Due to recent updates in the 5.0.3 dev branch Styles for Navigation Controls Login and Profile are not displayed inline

### Screenshots

image

### Additional Context

I have a PR about ready for the Blazor, Oqtane and Theme Creator themes that will resolve this issue.

### LINKED ISSUE #3762: Bug: Breakpoint for responsive design is not set the same as Bootstrap md 767.98px
### Issue

Breakpoint for responsive design is not set the same as Bootstrap md 767.98px leaving the toggle icon in odd places if at that point by chance.

### Screenshots

image

### PR DESCRIPTION
**Pull request by thabaum**
### Pull Request

Closes #3760
Closes #3762

This pull request will style the controls used for login, profile, dashboard and edit buttons along with any relating elements.  This css styling addition will keep the buttons on the same line and to the right side of the mobile screen using Flexbox.

### Screenshots
image
image

### Additional Context

Added a 5px margin on the right side of each of the control spans with the forms to space the buttons apart.

image

This PR will also fix this issue with responsive behavior for the navbar md breakpoint.

image

This is similar to PR #3736 which is more of an enhancement and will need re-based once discussed further or closed as it works with same files as this PR.  I can redo that one later once discussed as it introduces the "lg" instead of "md"

### CODE REVIEW

**Comment by sbwalker** [comment]
@thabaum I believe a much simpler solution to this problem is to add an inline-block style to the form surrounding a button:

```
               <form method="post" style="display:inline-block;" action="@logouturl" @formname="LogoutForm">
                   <input type="hidden" name="__RequestVerificationToken" value="@SiteState.AntiForgeryToken" />
                   <input type="hidden" name="returnurl" value="@returnurl" />
                   <button type="submit" class="btn btn-primary">@Localizer["Logout"]</button>
               </form>
```

produces:

image

This would be a non-breaking change for all existing themes which reference the  Login component.

The inline-block is a simple solution for any modules which want to convert interactive buttons to static form buttons.

An improvement to using a hardcoded style would be to introduce a class ie. app-inline-form which essentially provides the same behavior.

**Comment by thabaum** [comment]
@sbwalker did you see how it looks when it goes on top of navbar?

**Comment by sbwalker** [comment]
@thabaum yes, it looks fine:

image

It looks exactly the same way that it has always looked

**Comment by thabaum** [comment]
Right on, seems like that should be the way to go, except I dont like hard coding things in.  You would select it via `.controls-group form {}` I believe

**Comment by sbwalker** [comment]
closing in favor of #3763

**Pull request closed without merging**
