### PR TITLE
Updated to Blazor WebAssembly 3.2 preview 4

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by sbwalker** [comment]
Thank you for making these changes. I am going to hold off until tomorrow to merge them as I have to do a demo this evening. I assume this PR has been tested for both Blazor Server and Blazor WebAssembly?

**Comment by hishamco** [comment]
Please hold on, coz I need to change few things too. All the best in your demo

**Comment by sbwalker** [comment]
@hishamco to test WebAssembly all you need to do is set the value in the appsettings.json:

```
{
  "ConnectionStrings": {
    "DefaultConnection": ""
  },
  "Runtime": "WebAssembly"
}
```

**Comment by sbwalker** [comment]
@hishamco you asked me to wait before merging this PR - is it ready now?

**Comment by hishamco** [comment]
Sorry for late, I will have a look now ...

**Comment by hishamco** [comment]
I have an issue with the internet connection if I didn't reply withing an hour, you can run the app and merge the PR then

**Comment by hishamco** [comment]
@sbwalker you could merge now, I thought yesterday that there will be an issue, it's ok now

**Pull request merged**
