### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by sbwalker** [comment]
"Refactoring" does not provide any clue of what this PR is trying to accomplish. If there was any specific goals behind the PR it is good to provide the context so that it helps with the review of the code changes. Is this related to #245 or #280?

**Comment by hishamco** [comment]
Both, it would be nice if we can merge this after setup CI/CD to ensure it doesn't break anthing

**Comment by hishamco** [comment]
I will defer the conflict resolve until we provide CI/CD coz every time I fix it new PR is merged ;)

**Comment by hishamco** [comment]
Again, moving to code behind model will simplify the things and makes the views clear

**Comment by sbwalker** [comment]
@hishamco it sounds like you are saying that you have not tested these changes with a clean install ( ie. remove connectionstring and install new database ). If so, then I will definitely wait to merge them.

**Comment by hishamco** [comment]
> you have not tested these changes with a clean install ( ie. remove connectionstring and install new database )

Yep, I just build the entire solution to make sure that I didn't make something wrong, because if you look closely, what I did is very simple refactoring

**Comment by sbwalker** [comment]
It is a fairly simple refactoring - but this PR affects almost every UI in the application - which means every UI interaction should be regression tested. CI/CD would verify that the application installs successfully but at this point it will not be capable of any regression testing. It might be a good idea to attempt a clean local install and manually test each UI affected?

**Comment by hishamco** [comment]
> It might be a good idea to attempt a clean local install and manually test each UI affected?

I'm trying a fresh installation everything till now is working as expected ..

**Comment by sbwalker** [comment]
Are you able to deal with the latest conflicts and then I can merge this? Its a large PR and I don't want it to sit on the shelf too long or else it will become more difficult to merge

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
@sbwalker please squash & merge

**Comment by sbwalker** [comment]
This PR introduced 56 compilation errors when it was merged. It appears that a global search and replace was done for string.Empty which caused issues in every case where an escape sequence was being used to build a string ( ie. \" ). 

ie.            _openLabel += " for=\string.Empty + For + "\string.Empty;

I am curious how you were able to perform a clean install when the code will not even compile?

**Comment by hishamco** [comment]
Please let me check ...

**Comment by sbwalker** [comment]
I have fixed all of the compilation errors and will check in shortly. It appears they may have occurred when you were dealing with the merge conflicts.

**Comment by hishamco** [comment]
May be .. If you want me to send a PR for regression bug no problem I can do it now ... again I request you to setup CI/CD to avoid such issues

Thanks

**Pull request merged**
