### PR TITLE
Factored out Contants.*** Role into RoleNames.***

### PR DESCRIPTION
**Pull request by TonyValenti**
Renamed 'AllUsers' to 'Everyone'

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=805) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=805) before we can accept your contribution.<br/><br/>:x: TonyValenti [sign now](https://cla.dotnetfoundation.org/oqtane/oqtane.framework?pullRequest=805)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/oqtane/oqtane.framework?pullRequest=805) it.</sub>

**Comment by mikecasas** [comment]
I'm not against refactoring's like this, but it's going to break all my external modules. I know you included the ```Obsolete``` attribute.

If this is part of the movement to .NET 5, then I am ok with it.

My external controller code:

```
// GET api/<controller>/5
[HttpGet("{id}")]
[Authorize(Roles = Constants.RegisteredRole)]
public ReportViewer Get(int id)
{
  return _ReportViewers.GetReportViewer(id);
}

```

**Comment by TonyValenti** [comment]
@mikecasas What could I do different to make it not break?
Is it just breaking because it treats warnings as errors?

**Comment by mikecasas** [comment]
I meant it more in line that I would have to go and change all my modules - which I am not opposed to. It would be a simple find and replace.

I guess I just don't see the benefit - but that's me.

**Comment by hishamco** [comment]
The PR title is something and "Renamed 'AllUsers' to 'Everyone'" is another thing, could please filed an issue to describe the problem before you invest a time of something may not acceptable

Thanks

**Comment by sbwalker** [comment]
@mikecasas I am reviewing this PR and based on the fact that the current constants were not removed, I do not see where the breaking change is - are you able to explain? A breaking change is when your module throws a run-time error due to an incompatibility introduced in the framework. If what you are referring to is compilation warnings based on the Obsolete attributes it is not a breaking change as your module is still functional without any changes.

**Comment by mikecasas** [comment]
I mis-spoke, I should not have used the term breaking change.

**Comment by TonyValenti** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/

This article has a good description of breaking changes. I don’t believe the changes I made are breaking. 

Additionally, I would suggest adding the above article to the philosophy article and making that part of the official documentation in a markdown file.

**Pull request merged**
