### PR TITLE
Fix - return to url during login fail when returnurl contains "/"

### PR DESCRIPTION
**Pull request by chlupac**
Url was transformed to 
https://xxxx.yyy/login/!/returnurl=test/Detail
instead of
https://xxxx.yyy/login?returnurl=test/Detail

### CODE REVIEW

**Comment by sbwalker** [comment]
I am not sure if this is the correct fix as hardcoding the parameter name of "returnurl=" in the logic seems far too specific. It seems there is a more general problem that if a querystring parameter has a value which contains a "/" ( ie. a path delimiter ) then the utility method fails to interpret it correctly. Perhaps the returnurl value should be Url encoded in this case?

**Comment by chlupac** [comment]
Yes, URL encoding /decoding will be correct way, but I'ts more complicated and I'm not sure where should be decoding/encoding implemented.

**Comment by sbwalker** [comment]
See my edited comment above... I don't think url encoding is necessary after reviewing the code.

**Comment by chlupac** [comment]
ok. I will do it your way. Updated version.

**Comment by sbwalker** [comment]
Thank you @chlupac. We really need some better developer documentation to explain the usage for some framework APIs. @PoisnFang did a great job on the Url Parameter enhancement, but clearly there are a few edge cases which can cause challenges.

**Comment by PoisnFang** [comment]
Yes I see what is happening here... not something I had thoughy about during dev

**Comment by sbwalker** [comment]
@PoisnFang I dont think there is anything wrong with your solution - there are 2 fairly trivial options to handle this - either prefix the parameters with "?" or url encode the values so that they do not contain "/"

**Pull request merged**
