### PR TITLE
Implement Database Migrations and add Multi-Database Support

### PR DESCRIPTION
**Pull request by cnurse**
This Pull Request implements 2 related but separate features:

- Converting the Schema changes from DbUp to EF Core Migrations
- Adding support for additional Databases.

It implements the following changes:

- Adding Database Migrations for each of the existing SchemaVersions scripts from the initial version 1.0 release
- Adding a custom script to "migrate" any exisitng SchemaVersion table records to "initialise the EFMigrationsHistory table
- Adding a Migrations Framework so that it is not necessary to build Migrations for every supported Database, but takes advantage of EFCore's providers.
- Add a ne IOqtaneDatabase interface which identifies the Database being used
- Adding an implementation of IOqtaneDatabase for 5 Databases
- - SqlServer and LocalDB implemented in Oqtane.Server as these rpresent the existing databases supported
- - SqlLite, MySQL and PostGreSQL implemented in external projects as these are new databases
- Adding support in both the Installation Wizard and AddSite/Tenant components to dynamically load the appropriate fields for building the correct connection string for each database.
- Adding support to handle the custom naming schemes for each database type (PostGreSQL uses snake-casing, SQlServer uses Pascal casing)

These changes have been tested for new installs on all database types (SqlServer, Sqlite, MySQL, PostgreSQL) on both Windows and Mac (PostgreSQL and Sqlite), and for upgrades on SQL Server, as well as for adding new Tenants.

Enjoy!!

### CODE REVIEW

**Comment by hishamco** [comment]
Please fix the conflict, I may need to test and review the PR

Thanks

**Comment by cnurse** [comment]
@hishamco - I have resolved the conflicts, but please hold off committing this until I have had a chance to review it with @sbwalker 

Thanks

**Comment by hishamco** [comment]
Ok, please let me know when it's ready to review

Thanks again

**Comment by hishamco** [comment]
> @hishamco - I have resolved the conflicts, but please hold off committing this until I have had a chance to review it with @sbwalker

Seems @sbwalker merge this PR ;)

**Comment by sbwalker** [comment]
I reviewed the PR with @cnurse on the weekend, and there are still some changes required but we decided it would be best to merge it so that more people are able to participate in the testing.

**Comment by hishamco** [comment]
Thanks @cnurse for your efforts

**Pull request merged**
